const STORAGE_KEY = 'lostark-hideout-private-v3';
const LEGACY_KEY = 'lostark-hideout-private-v2';
const MAX_CHARACTERS = 8;
const BIBLE_CONNECTOR = 'https://lostark-bible-connector.seraph0226.workers.dev/character';
const CLASS_NAMES = ['Berserker','Destroyer','Gunlancer','Paladin','Slayer','Warrior','Arcanist','Arcana','Summoner','Sorceress','Bard','Gunslinger','Deadeye','Sharpshooter','Artillerist','Machinist','Striker','Wardancer','Scrapper','Soulfist','Glavier','Glaivier','Deathblade','Shadowhunter','Reaper','Artist','Aeromancer','Breaker','Valkyrie','Soul Eater','Souleater'];
const CLASS_ENGRAVINGS = {Artist:{support:['Full Bloom'],dps:['Recurrence']},Bard:{support:['Desperate Salvation'],dps:['True Courage']},Paladin:{support:['Blessed Aura'],dps:['Judgment']},Valkyrie:{support:['Blessed Aura'],dps:['Judgment']}};
const SUPPORT_ENGRAVINGS=['Expert','Awakening','Drops of Ether','Heavy Armor','Vital Point Hit','Magick Stream','Max MP Increase'];
const DPS_ENGRAVINGS=['Grudge','Adrenaline','Keen Blunt Weapon','Raid Captain','Master Brawler','Ambush Master','Cursed Doll','Mass Increase','Hit Master'];
const $=s=>document.querySelector(s);
function escapeHtml(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function formatNumber(v){return v==null||v===''?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:2})}
function setStatus(m){const e=$('#status');if(e)e.textContent=m}
function loadState(){try{const c=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(c&&Array.isArray(c.characters))return c;const l=JSON.parse(localStorage.getItem('lostark-hideout-private-v2')||'null');if(l&&Array.isArray(l.characters))return l}catch{}return{characters:[],testCharacter:null}}
const state=loadState();function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function parseBibleUrl(v){try{const u=new URL(v);if(u.protocol!=='https:'||u.hostname!=='lostark.bible')return null;const p=u.pathname.split('/').filter(Boolean);if(p.length<3||p[0].toLowerCase()!=='character')return null;return{url:u.href,region:p[1],name:decodeURIComponent(p.slice(2).join('/'))}}catch{return null}}
function makeDocument(h){if(typeof h!=='string'||!h.trim())throw Error('Bible returned an empty character page.');return new DOMParser().parseFromString(h,'text/html')}
function normalizedText(v){return String(v||'').replace(/\s+/g,' ').trim()}
function getLines(d){return(d.body?.textContent||'').split(/\n+/).map(normalizedText).filter(Boolean)}
function numberFrom(v){const m=String(v??'').replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m&&Number.isFinite(Number(m[0]))?Number(m[0]):null}
function findItemLevel(d,l){for(let i=0;i<l.length;i++)if(/^Item Level$/i.test(l[i]))for(let j=i+1;j<Math.min(l.length,i+8);j++){const n=numberFrom(l[j]);if(n>=1000&&n<=2000)return n}const m=normalizedText(d.body?.textContent).match(/Item Level\s*(\d{3,4}(?:\.\d+)?)/i);return m?numberFrom(m[1]):null}
function classFromText(text){const t=normalizedText(text);for(const n of [...CLASS_NAMES].sort((a,b)=>b.length-a.length)){const re=new RegExp(`(?:^|[^A-Za-z])${n.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\$&')}(?:[^A-Za-z]|$)`,'i');if(re.test(t))return n}return null}
function findClass(d,l,fallback){
  const target=normalizedText(fallback).toLowerCase();
  // The Bible profile header is authoritative. Its order is region -> continent/server -> class -> character name.
  // Check the lines immediately preceding the character name before inspecting any global metadata.
  for(let i=0;i<Math.min(l.length,80);i++){
    if(l[i].toLowerCase()===target || l[i].toLowerCase().replace(/^#\s*/,'')===target){
      for(let j=i-1;j>=Math.max(0,i-4);j--){const hit=classFromText(l[j]);if(hit&&hit!=='Warrior')return hit}
    }
  }
  // Prefer the header element containing the profile name and inspect its nearby text.
  const headings=[...d.querySelectorAll('h1,h2,h3')];
  const heading=headings.find(e=>normalizedText(e.textContent).replace(/^#\s*/,'').toLowerCase()===target);
  if(heading){
    const parent=heading.parentElement;
    const nearby=normalizedText(parent?.textContent||'');
    const hit=classFromText(nearby);if(hit&&hit!=='Warrior')return hit;
    let el=heading.previousElementSibling;for(let n=0;el&&n<4;n++,el=el.previousElementSibling){const h=classFromText(el.textContent);if(h&&h!=='Warrior')return h}
  }
  for(const el of d.querySelectorAll('[alt],[title],[aria-label],[data-class],[data-character-class]'))for(const attr of ['data-class','data-character-class','aria-label','title','alt']){const v=el.getAttribute?.(attr);const hit=classFromText(v);if(hit)return hit}
  for(const line of l.slice(0,40)){const hit=classFromText(line);if(hit)return hit}
  const body=normalizedText(d.body?.textContent||''),start=target?body.toLowerCase().indexOf(target):-1,local=start>=0?body.slice(Math.max(0,start-500),start+500):'',localHit=classFromText(local);if(localHit)return localHit;
  for(const s of d.scripts||[]){const hit=classFromText(s.textContent||'');if(hit)return hit}
  return 'Unknown'
}
function findProfileName(d,f){const c=[...d.querySelectorAll('h1')].map(e=>normalizedText(e.textContent)).filter(Boolean);return c[0]||f||'Unknown'}
function candidateNumbers(t){return(String(t).match(/\b\d{4,5}(?:\.\d{1,2})?\b/g)||[]).map(numberFrom).filter(n=>n>=4000&&n<=20000)}
function chooseSection(s,source){if(/chaos\s*dungeon/i.test(s)&&!/estimated\s*raid|current\s*loadout\s*\(\s*raid\s*\)/i.test(s))return null;const n=candidateNumbers(s);if(!n.length)return null;let score=/combat\s*power/i.test(s)?100:0;if(/estimated\s*raid|estimated_raid|estimatedraid|raid_merged/i.test(s))score+=80;if(/current\s*loadout\s*\(\s*raid\s*\)/i.test(s))score+=70;if(/chaos\s*dungeon/i.test(s))score-=1000;return score>=0?{value:n[0],source}:null}
function extractRaidCP(d){const sources=[normalizedText(d.body?.textContent),d.documentElement?.outerHTML||'',...([...d.scripts].map(s=>s.textContent||''))];for(const src of sources)for(const label of ['Estimated Raid Loadout','estimated_raid','estimatedRaid','raid_merged']){let i=0;while((i=src.toLowerCase().indexOf(label.toLowerCase(),i))>=0){const r=chooseSection(src.slice(i,i+5000),'Estimated Raid Loadout');if(r)return r;i+=label.length}}for(const src of sources)for(const label of ['Current Loadout (Raid)','current_raid','most_recent_raid']){let i=0;while((i=src.toLowerCase().indexOf(label.toLowerCase(),i))>=0){const r=chooseSection(src.slice(i,i+5000),'Current Loadout (Raid)');if(r)return r;i+=label.length}}return{value:null,source:'No acceptable raid CP found'}}
function extractPresetSnippet(d,preferred){const sources=[d.documentElement?.outerHTML||'',normalizedText(d.body?.textContent||''),...([...d.scripts].map(s=>s.textContent||''))];const labels=preferred==='Estimated Raid Loadout'?['Estimated Raid Loadout','estimated_raid','estimatedRaid','raid_merged']:['Current Loadout (Raid)','current_raid','most_recent_raid'];for(const src of sources)for(const label of labels){const i=src.toLowerCase().indexOf(label.toLowerCase());if(i>=0)return src.slice(i,i+12000)}return ''}
function detectRole(snippet,cls){if(!snippet)return 'Unknown';const s=snippet.toLowerCase(),spec=CLASS_ENGRAVINGS[cls];if(spec){if(spec.support.some(x=>s.includes(x.toLowerCase())))return 'Support';if(spec.dps.some(x=>s.includes(x.toLowerCase())))return 'DPS'}let support=0,dps=0;for(const x of SUPPORT_ENGRAVINGS)if(s.includes(x.toLowerCase()))support++;for(const x of DPS_ENGRAVINGS)if(s.includes(x.toLowerCase()))dps++;if(support>=2&&support>dps)return 'Support';if(dps>=2&&dps>support)return 'DPS';return 'Unknown'}
function extractBibleClassIcon(d,region,name){try{const target=`/character/${region}/${encodeURIComponent(name)}`.toLowerCase();for(const a of d.querySelectorAll('a[href]')){const href=(a.getAttribute('href')||'').toLowerCase();if(href===target||decodeURIComponent(href)===`/character/${region}/${name}`.toLowerCase()){const svg=a.querySelector('svg.size-14,svg[class*="size-14"]');if(svg)return svg.outerHTML}}}catch{}return ''}
function svgDataUrl(svg){return svg?`data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`:''}
function parseProfile(html,fallback,region){const d=makeDocument(html),l=getLines(d),cp=extractRaidCP(d),cls=findClass(d,l,fallback),classIcon=svgDataUrl(extractBibleClassIcon(d,region,fallback));return{name:findProfileName(d,fallback),class:cls,role:detectRole(extractPresetSnippet(d,cp.source==='Estimated Raid Loadout'?'Estimated Raid Loadout':'Current Loadout (Raid)'),cls),ilvl:findItemLevel(d,l),cp:cp.value,cpSource:cp.source,loadout:cp.source,classIcon,retrievedAt:new Date().toISOString()}}
async function fetchCharacter(c){let r;try{r=await fetch(`${BIBLE_CONNECTOR}?url=${encodeURIComponent(c.url)}`,{method:'GET',cache:'no-store',headers:{Accept:'application/json'}})}catch(e){throw Error(`Unable to reach the Bible connector: ${e.message||'network error'}`)}const raw=await r.text();let data;try{data=JSON.parse(raw)}catch{throw Error(`Bible connector returned non-JSON data (HTTP ${r.status}).`)}if(!r.ok||data.ok===false)throw Error(data.error||`Bible connector returned HTTP ${r.status}.`);return parseProfile(data.html||data.characterHtml||data.content||data.page,c.name,c.region)}
function classIconUrl(cls){const map={Berserker:'ClassIcon-Warrior-Berserker.png',Destroyer:'ClassIcon-Warrior-Destroyer.png',Gunlancer:'ClassIcon-Warrior-Gunlancer.png',Paladin:'ClassIcon-Warrior-Paladin.png',Slayer:'ClassIcon-Warrior-Slayer.png',Arcanist:'ClassIcon-Mage-Arcanist.png',Arcana:'ClassIcon-Mage-Arcanist.png',Summoner:'ClassIcon-Mage-Summoner.png',Sorceress:'ClassIcon-Mage-Sorceress.png',Bard:'ClassIcon-Mage-Bard.png',Gunslinger:'ClassIcon-Gunner-Gunslinger.png',Deadeye:'ClassIcon-Gunner-Deadeye.png',Sharpshooter:'ClassIcon-Gunner-Sharpshooter.png',Artillerist:'ClassIcon-Gunner-Artillerist.png',Machinist:'ClassIcon-Gunner-Artillerist.png',Striker:'ClassIcon-Martial Artist-Striker.png',Wardancer:'ClassIcon-Martial Artist-Wardancer.png',Scrapper:'ClassIcon-Martial Artist-Scrapper.png',Soulfist:'ClassIcon-Martial Artist-Soulfist.png',Glavier:'ClassIcon-Martial Artist-Glaivier.png',Glaivier:'ClassIcon-Martial Artist-Glaivier.png',Deathblade:'ClassIcon-Assassin-Deathblade.png',Shadowhunter:'ClassIcon-Assassin-Shadowhunter.png',Reaper:'ClassIcon-Assassin-Reaper.png','Soul Eater':'Icon Soul Eater.jpg',Souleater:'Icon Soul Eater.jpg',Artist:'ClassIcon-Specialist-Artist.png',Aeromancer:'ClassIcon-Specialist-Aeromancer.png'};return map[cls]?`https://lostark.fandom.com/wiki/Special:Redirect/file/${encodeURIComponent(map[cls])}`:''}
function correctedClassForCharacter(c){return c?.profile?.class||'Unknown'}
function iconForProfile(p){return p?.classIcon||classIconUrl(p?.class)||''}
function render(){const complete=state.characters.filter(c=>c.profile),il=complete.map(c=>c.profile.ilvl).filter(Number.isFinite),cp=complete.map(c=>c.profile.cp).filter(Number.isFinite);$('#playerCount').textContent=`${state.characters.length} / ${MAX_CHARACTERS}`;$('#avgIlvl').textContent=il.length?Math.round(il.reduce((a,b)=>a+b,0)/il.length):'—';$('#avgCp').textContent=cp.length?Math.round(cp.reduce((a,b)=>a+b,0)/cp.length).toLocaleString():'—';$('#dataMode').textContent='Bible profiles';$('#rosterNote').textContent='Only explicitly supplied character URLs are retrieved. Raid CP priority: Estimated Raid Loadout → Current Loadout (Raid). Chaos Dungeon Loadout is never used.';$('#roster').innerHTML=state.characters.length?state.characters.map(c=>{const p=c.profile||{},cls=correctedClassForCharacter(c),name=p.name||c.name,icon=iconForProfile(p);return`<article class="character"><div class="character-head"><div><h3 class="character-title">${icon?`<img class="class-icon" src="${icon}" alt="${escapeHtml(cls)}">`:''}<a class="character-bible-link" href="${escapeHtml(c.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(name)}</a></h3><div class="class">${escapeHtml(cls)}</div></div></div><div class="stats"><div class="stat">iLvl<b>${formatNumber(p.ilvl)}</b></div><div class="stat">CP<b>${formatNumber(p.cp)}</b></div></div><div class="privacy-note">Bible profile loaded · ${escapeHtml(p.loadout)} · CP source: ${escapeHtml(p.cpSource)}</div></article>`}).join(''):'<div class="empty-roster">No designated main characters have been added.</div>';renderSuggestions()}
function renderSuggestions(){return}
window.__hideoutState=state;window.__hideoutSaveState=saveState;window.__hideoutFetchCharacter=fetchCharacter;window.__hideoutRender=render;
})()