const STORAGE_KEY = 'lostark-hideout-private-v3';
const LEGACY_KEY = 'lostark-hideout-private-v2';
const REMOVE_CONFIRM_KEY = 'lostark-hideout-skip-remove-confirm-v1';
const MAX_CHARACTERS = 8;
const BIBLE_CONNECTOR = 'https://lostark-bible-connector.seraph0226.workers.dev/character';
const CLASS_NAMES = ['Berserker','Destroyer','Gunlancer','Paladin','Slayer','Warrior','Arcanist','Arcana','Summoner','Sorceress','Bard','Gunslinger','Deadeye','Sharpshooter','Artillerist','Machinist','Striker','Wardancer','Scrapper','Soulfist','Glavier','Glaivier','Deathblade','Shadowhunter','Reaper','Artist','Aeromancer','Breaker','Valkyrie','Soul Eater','Souleater'];
const $=s=>document.querySelector(s);
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function formatNumber(v){return v==null||v===''?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:2})}
function setStatus(m){const e=$('#status');if(e)e.textContent=m}
function loadState(){try{const c=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(c&&Array.isArray(c.characters))return c;const l=JSON.parse(localStorage.getItem(LEGACY_KEY)||'null');if(l&&Array.isArray(l.characters))return l}catch{}return{characters:[],testCharacter:null}}
const state=loadState();function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function parseBibleUrl(v){try{const u=new URL(v);if(u.protocol!=='https:'||u.hostname!=='lostark.bible')return null;const p=u.pathname.split('/').filter(Boolean);if(p.length<3||p[0].toLowerCase()!=='character')return null;return{url:u.href,region:p[1],name:decodeURIComponent(p.slice(2).join('/'))}}catch{return null}}
function makeDocument(h){if(typeof h!=='string'||!h.trim())throw Error('Bible returned an empty character page.');return new DOMParser().parseFromString(h,'text/html')}
function normalizedText(v){return String(v||'').replace(/\s+/g,' ').trim()}
function getLines(d){return(d.body?.textContent||'').split(/\n+/).map(normalizedText).filter(Boolean)}
function numberFrom(v){const m=String(v??'').replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m&&Number.isFinite(Number(m[0]))?Number(m[0]):null}
function findItemLevel(d,l){for(let i=0;i<l.length;i++)if(/^Item Level$/i.test(l[i]))for(let j=i+1;j<Math.min(l.length,i+8);j++){const n=numberFrom(l[j]);if(n>=1000&&n<=2000)return n}const m=normalizedText(d.body?.textContent).match(/Item Level\s*(\d{3,4}(?:\.\d+)?)/i);return m?numberFrom(m[1]):null}
function findClass(d,l){const text=(d.documentElement?.outerHTML||'')+'\n'+(d.body?.textContent||'');for(const n of CLASS_NAMES){const re=new RegExp(`(?:^|[^A-Za-z])${n.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\$&')}(?:[^A-Za-z]|$)`,'i');if(re.test(text))return n}return 'Unknown'}
function findProfileName(d,f){const c=[...d.querySelectorAll('h1,h2,[class*="character-name"],[class*="name"]')].map(e=>normalizedText(e.textContent)).filter(Boolean);return c[0]||f||'Unknown'}
function candidateNumbers(t){return(String(t).match(/\b\d{4,5}(?:\.\d{1,2})?\b/g)||[]).map(numberFrom).filter(n=>n>=4000&&n<=20000)}
function chooseSection(s,source){if(/chaos\s*dungeon/i.test(s)&&!/estimated\s*raid|current\s*loadout\s*\(\s*raid\s*\)/i.test(s))return null;const n=candidateNumbers(s);if(!n.length)return null;let score=/combat\s*power/i.test(s)?100:0;if(/estimated\s*raid|estimated_raid|estimatedraid|raid_merged/i.test(s))score+=80;if(/current\s*loadout\s*\(\s*raid\s*\)/i.test(s))score+=70;if(/chaos\s*dungeon/i.test(s))score-=1000;return score>=0?{value:n[0],source}:null}
function extractRaidCP(d){const sources=[normalizedText(d.body?.textContent),d.documentElement?.outerHTML||'',...([...d.scripts].map(s=>s.textContent||''))];for(const src of sources)for(const label of ['Estimated Raid Loadout','estimated_raid','estimatedRaid','raid_merged']){let i=0;while((i=src.toLowerCase().indexOf(label.toLowerCase(),i))>=0){const r=chooseSection(src.slice(i,i+3000),'Estimated Raid Loadout');if(r)return r;i+=label.length}}for(const src of sources)for(const label of ['Current Loadout (Raid)','current_raid','most_recent_raid']){let i=0;while((i=src.toLowerCase().indexOf(label.toLowerCase(),i))>=0){const r=chooseSection(src.slice(i,i+3000),'Current Loadout (Raid)');if(r)return r;i+=label.length}}return{value:null,source:'No acceptable raid CP found'}}
function parseProfile(html,fallback){const d=makeDocument(html),l=getLines(d),cp=extractRaidCP(d);return{name:findProfileName(d,fallback),class:findClass(d,l),ilvl:findItemLevel(d,l),cp:cp.value,cpSource:cp.source,loadout:cp.source,retrievedAt:new Date().toISOString()}}
async function fetchCharacter(c){let r;try{r=await fetch(`${BIBLE_CONNECTOR}?url=${encodeURIComponent(c.url)}`,{method:'GET',cache:'no-store',headers:{Accept:'application/json'}})}catch(e){throw Error(`Unable to reach the Bible connector: ${e.message||'network error'}`)}const raw=await r.text();let data;try{data=JSON.parse(raw)}catch{throw Error(`Bible connector returned non-JSON data (HTTP ${r.status}).`)}if(!r.ok||data.ok===false)throw Error(data.error||`Bible connector returned HTTP ${r.status}.`);return parseProfile(data.html||data.characterHtml||data.content||data.page,c.name)}
function classIconUrl(cls){const map={"Berserker":"berserker","Destroyer":"destroyer","Gunlancer":"gunlancer","Paladin":"paladin","Slayer":"slayer","Arcanist":"arcanist","Arcana":"arcana","Summoner":"summoner","Sorceress":"sorceress","Bard":"bard","Gunslinger":"gunslinger","Deadeye":"deadeye","Sharpshooter":"sharpshooter","Artillerist":"artillerist","Machinist":"machinist","Striker":"striker","Wardancer":"wardancer","Scrapper":"scrapper","Soulfist":"soulfist","Glavier":"glavier","Glaivier":"glavier","Deathblade":"deathblade","Shadowhunter":"shadowhunter","Reaper":"reaper","Artist":"artist","Aeromancer":"aeromancer","Breaker":"breaker","Valkyrie":"valkyrie","Soul Eater":"soul-eater","Souleater":"soul-eater"};return map[cls]?`https://lostark.bible/_next/image?url=%2Fimages%2Fclasses%2F${map[cls]}.png&w=64&q=75`:''}
function classLabel(p){const icon=classIconUrl(p?.class);return`${icon?`<img class="class-icon" src="${icon}" alt="">`:''}<span>${escapeHtml(p?.class||'Profile pending')}</span>`}
function render(){const complete=state.characters.filter(c=>c.profile),il=complete.map(c=>c.profile.ilvl).filter(Number.isFinite),cp=complete.map(c=>c.profile.cp).filter(Number.isFinite);$('#playerCount').textContent=`${state.characters.length} / ${MAX_CHARACTERS}`;$('#avgIlvl').textContent=il.length?Math.round(il.reduce((a,b)=>a+b,0)/il.length):'—';$('#avgCp').textContent=cp.length?Math.round(cp.reduce((a,b)=>a+b,0)/cp.length).toLocaleString():'—';$('#dataMode').textContent='Bible profiles';$('#rosterNote').textContent='Only explicitly supplied character URLs are retrieved. Raid CP priority: Estimated Raid Loadout → Current Loadout (Raid). Chaos Dungeon Loadout is never used.';$('#roster').innerHTML=state.characters.length?state.characters.map(c=>{const p=c.profile;return`<article class="character"><div class="character-head"><div><h3>${classIconUrl(p?.class)?`<img class="class-icon" src="${classIconUrl(p.class)}" alt="">`:''}${escapeHtml(p?.name||c.name)}</h3><div class="class">${classLabel(p)}</div></div><button class="remove-character" data-id="${escapeHtml(c.id)}" type="button">Remove</button></div><div class="stats"><div class="stat">iLvl<b>${formatNumber(p?.ilvl)}</b></div><div class="stat">CP<b>${formatNumber(p?.cp)}</b></div></div><div class="privacy-note">${p?`Bible profile loaded · ${escapeHtml(p.loadout)} · CP source: ${escapeHtml(p.cpSource)}`:escapeHtml(c.profileError||'Profile pending')}</div></article>`}).join(''):'<div class="empty-roster">No designated main characters have been added.</div>';document.querySelectorAll('.remove-character').forEach(b=>b.addEventListener('click',()=>removeCharacter(b.dataset.id)));renderSuggestions()}
function renderSuggestions(){const complete=state.characters.filter(c=>c.profile);if(!complete.length){$('#suggestedParties').innerHTML='<div class="empty-roster">Add specific character profiles to generate the party setup.</div>';return}const s=[...complete].sort((a,b)=>(b.profile.cp||0)-(a.profile.cp||0)),a=s.filter((_,i)=>i%2===0).slice(0,4),b=s.filter((_,i)=>i%2===1).slice(0,4),party=(title,m)=>`<article class="party"><h3>${title}</h3><div class="score">${m.length}/4 slots filled</div><div class="slots">${m.map(c=>`<div class="slot"><h4>${classIconUrl(c.profile.class)?`<img class="class-icon" src="${classIconUrl(c.profile.class)}" alt="">`:''}${escapeHtml(c.profile.name)}</h4><small>${escapeHtml(c.profile.class)} · iLvl ${formatNumber(c.profile.ilvl)} · CP ${formatNumber(c.profile.cp)}</small></div>`).join('')||'<div class="slot"><small>No characters assigned.</small></div>'}</div></article>`;$('#suggestedParties').innerHTML=party('Party 1',a)+party('Party 2',b)}
async function refreshProfiles(){if(!state.characters.length)return setStatus('Add at least one character first.');setStatus('Refreshing character profiles…');let ok=0,failed=0;for(const c of state.characters)try{c.profile=await fetchCharacter(c);delete c.profileError;ok++}catch(e){c.profileError=e.message;failed++}saveState();render();setStatus(failed?`Refreshed ${ok}; ${failed} failed.`:`Refreshed ${ok} profile${ok===1?'':'s'} from Bible.`)}
function removeCharacter(id){const c=state.characters.find(x=>x.id===id);if(!c)return;if(localStorage.getItem(REMOVE_CONFIRM_KEY)==='1')return performRemove(c);const o=document.createElement('div');o.className='remove-modal';o.innerHTML=`<div class="remove-modal-card"><h2>Remove character?</h2><p>Are you sure you want to remove <strong>${escapeHtml(c.name)}</strong>?</p><div class="remove-modal-actions"><button class="remove-cancel">Cancel</button><button class="remove-confirm">Remove Character</button></div></div>`;document.body.appendChild(o);o.querySelector('.remove-cancel').onclick=()=>o.remove();o.querySelector('.remove-confirm').onclick=()=>{o.remove();performRemove(c)}}function performRemove(c){state.characters=state.characters.filter(x=>x.id!==c.id);saveState();render()}
function init(){const add=$('#addCharacterBtn');if(add)add.onclick=()=>{if(state.characters.length>=MAX_CHARACTERS)return setStatus(`Maximum of ${MAX_CHARACTERS} characters reached.`);const p=parseBibleUrl($('#characterUrl').value.trim());if(!p)return setStatus('Enter a valid lostark.bible character URL.');if(state.characters.some(c=>c.url===p.url))return setStatus('That character is already added.');state.characters.push({...p,id:crypto.randomUUID(),profile:null});saveState();$('#characterUrl').value='';render();setStatus('Character added. Click Refresh Profiles.')};$('#refreshBtn').onclick=refreshProfiles;$('#optimizeBtn').onclick=()=>{renderSuggestions();setStatus('Parties refreshed.')};render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
