const KEY='lostark-hideout-private-v2';
const MAX_CHARACTERS=8;
const state=loadState();
const $=s=>document.querySelector(s);
function loadState(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x&&Array.isArray(x.characters)?x:{characters:[],testCharacter:null}}catch{return{characters:[],testCharacter:null}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function fmt(v){return v==null||v===''?'—':Number(v).toLocaleString()}
function bibleUrl(v){try{const u=new URL(v);if(u.protocol!=='https:'||u.hostname!=='lostark.bible'||!u.pathname.startsWith('/character/'))return null;const parts=u.pathname.split('/').filter(Boolean);if(parts.length<3)return null;return{url:u.href,region:parts[1],name:decodeURIComponent(parts.slice(2).join('/'))}}catch{return null}}
function render(){const chars=state.characters;const il=chars.map(x=>x.profile?.ilvl).filter(Number.isFinite),cp=chars.map(x=>x.profile?.cp).filter(Number.isFinite);$('#playerCount').textContent=`${chars.length} / ${MAX_CHARACTERS}`;$('#avgIlvl').textContent=il.length?Math.round(il.reduce((a,b)=>a+b,0)/il.length):'—';$('#avgCp').textContent=cp.length?Math.round(cp.reduce((a,b)=>a+b,0)/cp.length).toLocaleString():'—';$('#dataMode').textContent='Local profiles';$('#rosterNote').textContent='Only explicitly supplied character URLs are stored locally. No roster/account-wide data is imported.';$('#roster').innerHTML=chars.map(c=>`<article class="character"><h3>${esc(c.name)}</h3><div class="class">${esc(c.profile?.class||'Profile pending')}</div><div class="stats"><div class="stat">iLvl<b>${fmt(c.profile?.ilvl)}</b></div><div class="stat">CP<b>${fmt(c.profile?.cp)}</b></div></div><div class="privacy-note">${c.profile?'Profile loaded':'Awaiting secure Bible connector'}</div></article>`).join('')||'<div class="empty-roster">No designated main characters have been added.</div>';renderSuggestions()}
function renderSuggestions(){const el=$('#suggestedParties');if(!state.characters.length){el.innerHTML='<div class="empty-roster">Add specific character profiles to generate the two-party optimization.</div>';return}el.innerHTML='<article class="party"><h3>Optimization engine</h3><div class="score">Waiting for complete character profiles</div><p class="privacy-note">The optimizer will evaluate individual character strength, Ark Grid, Ark Passive, engravings, gems, support value, and class synergies together. It will then solve the best 4 + 4 partition.</p></article><article class="party"><h3>Privacy boundary</h3><div class="score">Character-specific only</div><p class="privacy-note">No roster/siblings/account-wide endpoint is used. The secure Bible retrieval layer must be connected before real profile data is fetched.</p></article>'}
$('#addCharacterBtn').onclick=()=>{if(state.characters.length>=MAX_CHARACTERS){alert(`Maximum of ${MAX_CHARACTERS} designated characters reached.`);return}const parsed=bibleUrl($('#characterUrl').value.trim());if(!parsed){$('#status').textContent='Enter a valid lostark.bible character URL';return}if(state.characters.some(c=>c.url===parsed.url)){ $('#status').textContent='That character is already added';return}state.characters.push({id:crypto.randomUUID(),...parsed,profile:null});save();$('#characterUrl').value='';$('#status').textContent='Character added locally; profile retrieval is pending';render()};
$('#refreshBtn').onclick=()=>{$('#status').textContent='Secure Bible connector is not connected yet';};
$('#optimizeBtn').onclick=()=>{$('#status').textContent=state.characters.length<2?'Add at least two characters first':'Complete character profiles are required before optimization';renderSuggestions()};
$('#compareBtn').onclick=()=>{const parsed=bibleUrl($('#testCharacterUrl').value.trim());if(!parsed){$('#status').textContent='Enter a valid Bible character URL for the test character';return}state.testCharacter=parsed;save();$('#comparison').innerHTML=`<div class="comparison-grid"><div class="comparison-card"><span>Current pool</span><b>${state.characters.length} characters</b></div><div class="comparison-card"><span>Test character</span><b>${esc(parsed.name)}</b></div><div class="comparison-card"><span>Result</span><b>Awaiting profile</b><div class="delta">No percentage is shown until both configurations have complete character profiles.</div></div></div>`;$('#status').textContent='Test character added locally; profile retrieval is pending'};
$('#shareBtn').onclick=()=>{alert('Private sharing is intentionally disabled until the secure data layer is implemented. The current public GitHub Pages version will not publish character profiles.')};
render();