const KEY='lostark-hideout-private-v1';
const blank={players:[],parties:2,updatedAt:null};
let state=load();
const $=s=>document.querySelector(s);
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x&&Array.isArray(x.players)?x:structuredClone(blank)}catch{return structuredClone(blank)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function fmt(v){return v==null||v===''?'—':Number(v).toLocaleString()}
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
// Loadout policy: Estimated Raid Loadout first; Current Loadout (Raid) second; never Chaos Dungeon Loadout.
function selectRaidLoadout(loadouts){if(!Array.isArray(loadouts))return null;const n=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,' ');return loadouts.find(x=>/estimated\s+raid\s+loadout/.test(n(x.name||x.label||x.type)))||loadouts.find(x=>/current\s+loadout\s+raid/.test(n(x.name||x.label||x.type)))||null}
function applyRow(p,row){const sets=row.loadouts||row.configurations||row.builds;const raid=selectRaidLoadout(sets);const s=raid||row;p.class=s.class||s.className||row.class||row.className||p.class||'—';p.ilvl=Number(s.ilvl??s.itemLevel??row.ilvl??row.itemLevel??p.ilvl)||null;p.cp=Number(s.cp??s.combatPower??row.cp??row.combatPower??p.cp)||null}
function render(){const il=state.players.map(p=>p.ilvl).filter(Number.isFinite),cp=state.players.map(p=>p.cp).filter(Number.isFinite);$('#playerCount').textContent=state.players.length;$('#avgIlvl').textContent=il.length?Math.round(il.reduce((a,b)=>a+b,0)/il.length):'—';$('#avgCp').textContent=cp.length?Math.round(cp.reduce((a,b)=>a+b,0)/cp.length).toLocaleString():'—';$('#roster').innerHTML=state.players.map(p=>`<article class="character" draggable="true" data-id="${esc(p.id)}"><h3>${esc(p.name)}</h3><div class="class">${esc(p.class||'—')}</div><div class="stats"><div class="stat">iLvl<b>${fmt(p.ilvl)}</b></div><div class="stat">CP<b>${fmt(p.cp)}</b></div></div></article>`).join('')||'<div class="empty-roster">No characters have been added.</div>';document.querySelectorAll('.character').forEach(e=>e.addEventListener('dragstart',x=>x.dataTransfer.setData('text/plain',e.dataset.id)));$('#parties').innerHTML=Array.from({length:state.parties},(_,party)=>`<article class="party"><h3>Party ${party+1}</h3><div class="slots">${Array.from({length:4},(_,slot)=>{const p=state.players.filter(x=>x.party===party)[slot];return `<div class="slot" data-party="${party}">${p?`<h4>${esc(p.name)}</h4><small>${esc(p.class||'—')} · ${fmt(p.ilvl)} · ${fmt(p.cp)} CP</small>`:'<span class="empty">Drop player here</span>'}</div>`}).join('')}</div></article>`).join('');document.querySelectorAll('.slot').forEach(e=>{e.addEventListener('dragover',x=>{x.preventDefault();e.classList.add('over')});e.addEventListener('dragleave',()=>e.classList.remove('over'));e.addEventListener('drop',x=>{x.preventDefault();e.classList.remove('over');const p=state.players.find(q=>q.id===x.dataTransfer.getData('text/plain'));if(p){p.party=Number(e.dataset.party);save();render()}})})}
$('#addCharacterBtn').onclick=()=>{const name=prompt('Character name');if(!name?.trim())return;const n=name.trim();if(state.players.some(p=>p.name.toLowerCase()===n.toLowerCase()))return;state.players.push({id:crypto.randomUUID(),name:n,class:'—',ilvl:null,cp:null,party:0});save();render()};
$('#addPartyBtn').onclick=()=>{state.parties++;save();render()};
$('#refreshBtn').onclick=()=>{$('#status').textContent='No runtime connector configured yet';};
render();