(()=>{'use strict';
const clean=s=>String(s??'').replace(/\s+/g,' ').trim(),SUPPORTS=new Set(['Bard','Artist','Paladin','Valkyrie']);
let lastKey='',loading=false;
const LABELS={damage:'Damage',mana:'Mana',crit:'Critical Rate',critDamage:'Critical Damage',attackSpeed:'Attack Speed',attackPower:'Attack Power',supportAmplification:'Support Amplification',positional:'Positional Damage'};
const general=()=>document.getElementById('generalOptimization')?.checked!==false&&window.LostArkOptimizerMode?.general!==false;
const pct=v=>{let n=Number(v);if(!Number.isFinite(n))return'Unavailable';if(n>=0&&n<=1)n*=100;return n.toFixed(2)+'%'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function encName(){try{let n=clean(window.LostArkEncounterScoring?.profile?.()?.name);if(n)return n}catch{}return clean(document.getElementById('raidSpecificSelect')?.selectedOptions?.[0]?.textContent)||'Selected encounter'}
function profile(c){return c.profile||c.data||{}}
function roster(){try{return(JSON.parse(localStorage.getItem('lostark-hideout-private-v3')||'{}').characters||[]).filter(c=>c&&c.id)}catch{return[]}}
function build(c){try{return window.LostArkBuildProfilesV3?.get(c.url)||window.LostArkBuildProfilesV2?.get(c.url)||{}}catch{return{}}}
function text(c){const p=profile(c),b=build(c);return clean([p.rawText,p.text,p.characterText,p.arkGridText,p.arkPassiveText,p.engravingsText,p.gemsText,p.tripodsText,b.text,b.className,b.engravings?.join(' '),b.grid?.map(x=>x.name+' '+x.points).join(' '),b.arkPassive?.map(x=>x.name+' '+x.level).join(' ')].filter(Boolean).join(' ')).toLowerCase()}
function cls(c){const p=profile(c),b=build(c),v=clean(p.class||p.className||p.characterClass||b.className);if(v&&v.toLowerCase()!=='unknown')return({'Soul Eater':'Souleater','Arcana':'Arcanist','Glavier':'Glaivier'}[v]||v);const t=text(c);for(const[n,r]of [['Summoner',/\bsummoner\b|master summoner|ancient spear/],['Souleater',/souleater|soul eater|full moon harvester|night.?s edge/],['Arcanist',/arcanist|arcana|empress grace|emperor.?s decree/],['Glaivier',/glaivier|glavier|pinnacle|control/],['Bard',/\bbard\b|desperate salvation|true courage/],['Artist',/\bartist\b|full bloom|recurrence/],['Paladin',/\bpaladin\b|blessed aura/],['Valkyrie',/\bvalkyrie\b/]])if(r.test(t))return n;return'Unknown'}
function role(c){return profile(c).role==='Support'||SUPPORTS.has(cls(c))?'Support':'DPS'}
function info(c){const p=profile(c);return{name:clean(p.name||c.name)||'Unknown',cls:cls(c),role:role(c),cp:Number(p.cp??p.combatPower)||0}}
function pos(c){const b=build(c),t=text(c);if(b.positional&&b.positional!=='Unknown')return b.positional;if(/ambush master|back attack/.test(t))return'Back Attack';if(/master brawler|front attack/.test(t))return'Front Attack';if(/hit master|master summoner/.test(t))return'Hit Master';return'Unknown'}
function effects(c){try{return window.LostArkPartySynergyAuthorityV1?.provided?.(info(c).cls,build(c),text(c))||[]}catch{return[]}}
function weight(c,t){const x=text(c),p=pos(c);let w=1;if(t==='crit'&&/keen blunt|adrenaline|burst|full moon/.test(x))w+=.35;if(t==='critDamage'&&/keen blunt|burst/.test(x))w+=.30;if(t==='attackSpeed'&&/raid captain|swiftness/.test(x))w+=.35;if(t==='positional')w=p==='Back Attack'||p==='Front Attack'?1.35:p==='Hit Master'?.55:.85;if(t==='mana')w=/summoner|mana|boundless/.test(x)?1.55:.2;if(t==='damage'&&/summoner/.test(x))w+=.10;return w}
function supportEffects(c){switch(info(c).cls){case'Bard':return[{type:'supportAmplification',value:.10},{type:'mana',value:.12},{type:'attackSpeed',value:.035}];case'Artist':return[{type:'supportAmplification',value:.10},{type:'mana',value:.08},{type:'attackSpeed',value:.04}];case'Paladin':return[{type:'supportAmplification',value:.10},{type:'damage',value:.03}];case'Valkyrie':return[{type:'supportAmplification',value:.095},{type:'attackSpeed',value:.06}];default:return[{type:'supportAmplification',value:.09}]}}
function supportUptime(p,t){const s=p.find(x=>role(x)==='Support');if(!s)return 0;const ps=p.filter(x=>role(x)==='DPS').map(pos).filter(Boolean),mixed=new Set(ps).size>1,sc=info(s).cls;let u=(sc==='Paladin'||sc==='Valkyrie')?(mixed?.94:.99):(mixed?.76:.95);if((sc==='Bard'||sc==='Artist')&&pos(t)==='Hit Master'&&mixed)u-=.05;return Math.max(.60,Math.min(1,u))}
function contribution(p,t){const cp=info(t).cp,b=build(t),fit=(b.engravings?.length?.valueOf()?0.004:0)+(b.grid?.length?.valueOf()?0.004:0)+(b.arkPassive?.length?.valueOf()?0.004:0)+(/master summoner|communication overflow/.test(text(t))?0.002:0);let sy=0,su=0,details=[];for(const src of p.filter(x=>x!==t&&role(x)==='DPS'))for(const e of effects(src)){const v=cp*Number(e.magnitude??e.value||0)*weight(t,e.type);sy+=v;details.push({source:info(src).name,type:e.type,value:v,group:'synergy'})}const s=p.find(x=>role(x)==='Support');if(s){const u=supportUptime(p,t);for(const e of supportEffects(s)){const v=cp*e.value*weight(t,e.type)*u;su+=v;details.push({source:info(s).name,type:e.type,value:v,group:'support'})}}return{base:cp,total:cp+cp*fit+sy+su,synergy:sy,support:su,details}}
function memberObject(el){const n=clean(el.querySelector('.party-character-link')?.textContent||el.querySelector('.character-name')?.textContent||el.querySelector('.party-name')?.textContent);return n?roster().find(c=>clean(profile(c).name||c.name).toLowerCase()===n.toLowerCase()):null}
function parties(){const root=document.getElementById('suggestedParties');if(!root)return[];const groups=[...root.querySelectorAll('.authoritative-party,.party,.party-group,.optimized-party')];const out=groups.map(g=>[...g.querySelectorAll('.party-member')].map(memberObject).filter(Boolean)).filter(p=>p.length===4);if(out.length)return out;const all=[...root.querySelectorAll('.party-member')].map(memberObject).filter(Boolean);return all.length===8?[all.slice(0,4),all.slice(4)]:[]}
function renderGeneral(){if(!general())return;for(const p of parties())for(const t of p)if(role(t)==='DPS'){const n=info(t).name.toLowerCase(),m=[...document.querySelectorAll('#suggestedParties .party-member')].find(x=>clean(x.querySelector('.party-character-link')?.textContent||x.querySelector('.character-name')?.textContent||x.querySelector('.party-name')?.textContent).toLowerCase()===n),card=m?.querySelector('.character-hover-breakdown');if(!card)continue;const x=contribution(p,t),b=x.base||1,rows=x.details.map(d=>`<div class="chb-synergy">${esc(LABELS[d.type]||d.type)} from ${esc(d.source)}: ${d.value>=0?'+':''}${Math.round(d.value).toLocaleString()} estimated contribution · ${(d.value/b*100).toFixed(2)}% of base power</div>`).join('');card.className='character-hover-breakdown chb-canonical-dps';card.innerHTML=`<div class="chb-head"><strong>${esc(info(t).name)}</strong><span>CP ${Math.round(b).toLocaleString()} · Contribution ${Math.round(x.total).toLocaleString()}</span></div><div class="chb-stats"><span>Party Synergy +${(x.synergy/b*100).toFixed(2)}%</span><span>Support Impact +${(x.support/b*100).toFixed(2)}%</span></div><div class="chb-detail">${rows||'No direct party effects detected.'}</div>`}}
function clearGeneralSupportDetail(){if(!general())return;document.querySelectorAll('.character-hover-breakdown .chb-detail').forEach(d=>{if(/observed median support uptime|^AP:|^Brand:|^H\.A\. Skill:|^Identity:/i.test(clean(d.textContent)))d.remove()})}
async function supportEnsure(){const api=window.LostArkSupportStats,mode=window.LostArkOptimizerMode||{},enc=mode.encounter;if(!api||!enc||general())return;const key=JSON.stringify({id:enc.id,boss:enc.boss,difficulty:enc.difficulty,label:enc.label});if(key===lastKey&&window.__LOSTARK_SUPPORT_STATS__?.ok)return;if(loading)return;loading=true;try{const r=await api.fetch(enc);if(r?.ok){window.__LOSTARK_SUPPORT_STATS__=r;lastKey=key}else lastKey=''}catch{lastKey=''}finally{loading=false}}
function supportPaint(m){const card=m.querySelector('.character-hover-breakdown');if(!card||clean(m.querySelector('.party-role-label')?.textContent).toLowerCase()!=='support')return;const api=window.LostArkSupportStats,s=api?.summary?.([m.querySelector('.class-icon')?.alt,m.dataset.class,m.querySelector('[data-class]')?.dataset.class,m.querySelector('.party-class-label')?.dataset.class].map(clean).find(x=>SUPPORTS.has(x))||'');if(!s)return;let d=[...card.querySelectorAll('.chb-detail')].find(x=>/observed median support uptime/i.test(clean(x.textContent)));if(!d){d=document.createElement('div');d.className='chb-detail';card.appendChild(d)}d.innerHTML=`<div><strong>Observed median support uptime</strong></div><div>${clean(encName())}</div><div>AP: ${pct(s.ap)} - Brand: ${pct(s.brand)} - H.A. Skill: ${pct(s.ha)} - Identity: ${pct(s.identity)}</div>`}
function encName(){try{let n=clean(window.LostArkEncounterScoring?.profile?.()?.name);if(n)return n}catch{}return clean(document.getElementById('raidSpecificSelect')?.selectedOptions?.[0]?.textContent)||'Selected encounter'}
function css(){let s=document.getElementById('hover-fix-v20-style');if(!s){s=document.createElement('style');s.id='hover-fix-v20-style';document.head.appendChild(s)}s.textContent='.chb-canonical-dps{width:430px!important;text-align:left}.chb-canonical-dps .chb-head{display:flex;justify-content:space-between;gap:10px;margin-bottom:5px}.chb-canonical-dps .chb-stats{display:flex;gap:16px;margin:3px 0 5px}.chb-canonical-dps .chb-detail{margin-top:5px}.chb-canonical-dps .chb-synergy{display:block;margin:2px 0}'}
function render(){if(general()){clearGeneralSupportDetail();renderGeneral()}else document.querySelectorAll('#suggestedParties .party-member').forEach(supportPaint);supportEnsure()}
function start(){css();render();const root=document.getElementById('suggestedParties')||document.body;let timer;const schedule=()=>{clearTimeout(timer);timer=setTimeout(render,30)};new MutationObserver(schedule).observe(root,{childList:true,subtree:true,characterData:true});document.addEventListener('mouseover',e=>{if(e.target.closest?.('#suggestedParties .party-member'))schedule()},true);[0,50,100,200,400,800,1500,3000].forEach(ms=>setTimeout(render,ms));setInterval(render,250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
