/* Lost Ark Hideout — build-aware party optimizer v8. */
(()=>{
const STORAGE='lostark-hideout-private-v3', PARTY='lostark-hideout-party-assignments-v2';
const CONNECTOR='https://lostark-hideout-connector.seraph0226.workers.dev/character';
const SUPPORTS=new Set(['Bard','Artist','Paladin','Valkyrie']);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Math.round(Number(n)||0).toLocaleString();
const pct=n=>`${n>=0?'+':''}${n.toFixed(2)}%`;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function state(){try{return JSON.parse(localStorage.getItem(STORAGE)||'null')||{characters:[]}}catch{return{characters:[]}}}
function chars(){return(state().characters||[]).filter(c=>c&&c.profile)}
function assignments(){try{const a=JSON.parse(localStorage.getItem(PARTY)||'null');if(a&&Array.isArray(a.party1)&&Array.isArray(a.party2))return a}catch{}return{party1:[],party2:[]}}
function save(a){localStorage.setItem(PARTY,JSON.stringify(a))}
function identity(c){const p=c.profile||{},cards=[...document.querySelectorAll('#roster .character')],card=cards.find(x=>x.querySelector('.remove-character')?.dataset.id===c.id),cls=(card?.querySelector('.class')?.textContent||p.class||'Unknown').trim();return{name:card?.querySelector('.character-bible-link')?.textContent?.trim()||p.name||c.name||'',cls,role:p.role==='Support'||SUPPORTS.has(cls)?'Support':'DPS',il:Number(p.ilvl)||0,cp:Number(p.cp)||0,url:c.url}}
function norm(s){return String(s||'').replace(/\s+/g,' ').trim()}
function num(s){const m=String(s||'').replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):null}
function metric(text,label){const re=new RegExp(label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'[^%]{0,100}([+-]?\\d+(?:\\.\\d+)?)%','i'),m=text.match(re);return m?Number(m[1]):0}
function buildText(c){const b=c.profile?.optimizerBuild||{};return norm([b.text,b.snippet,b.engravingText,b.arkGridText,b.arkPassiveText].filter(Boolean).join(' '))}
function buildMetrics(c){const p=c.profile||{},t=buildText(c),x={arkPassive:metric(t,'Ark Passive'),arkGrid:metric(t,'Ark Grid'),engravings:metric(t,'Engravings'),accessory:metric(t,'Accessory Effects'),bracelet:metric(t,'Bracelet Effects'),gems:metric(t,'Gems'),raw:t};return x}
function classTraits(c){const x=identity(c),t=buildText(c).toLowerCase(),m=buildMetrics(c),out={crit:0,critDamage:0,attackSpeed:0,damage:0,attackPower:0,positional:0,mana:0,supportAmplification:0};
const add=(k,v)=>out[k]+=v;
if(x.role==='Support')return out;
const cls=x.cls.toLowerCase();
if(/wardancer|striker|glavier|glaivier|souls?fist|aeromancer/.test(cls))add('crit',.010);
if(/glavier|glaivier|deathblade|souleater|soul eater/.test(cls))add('critDamage',.009);
if(/wardancer|striker|deathblade|bard|artist|valkyrie/.test(cls))add('attackSpeed',.006);
if(/gunlancer|destroyer|berserker|slayer|breaker/.test(cls))add('damage',.010);
if(/deathblade|reaper|shadowhunter|sou?leater|scrapper/.test(cls))add('positional',.008);
if(/gunslinger|deadeye|arcanist|arcana|sorceress|summoner|artillerist|machinist|sharpshooter|aeromancer/.test(cls))add('crit',.008);
if(/summoner/.test(cls))add('mana',.003);
if(/raid captain|mass increase|grudge/.test(t))add('attackSpeed',.004);
if(/keen blunt weapon/.test(t))add('critDamage',.004);
if(/ambush master|master brawler/.test(t))add('positional',.004);
if(/adrenaline/.test(t))add('crit',.004);
if(/hit master/.test(t))add('damage',.003);
if(/ark grid/.test(t)&&m.arkGrid>0)add('damage',Math.min(.012,m.arkGrid/5000));
return out}
function supportEffects(c){const cls=identity(c).cls.toLowerCase();if(cls==='bard')return{supportAmplification:.050,attackSpeed:.008,critDamage:.004};if(cls==='artist')return{supportAmplification:.047,mana:.006,attackSpeed:.004};if(cls==='paladin')return{supportAmplification:.052,damage:.004};if(cls==='valkyrie')return{supportAmplification:.049,attackSpeed:.006};return{supportAmplification:.045}}
function sensitivity(c,s){const t=buildText(c).toLowerCase(),x=identity(c).cls.toLowerCase(),v={crit:1,critDamage:1,attackSpeed:1,damage:1,attackPower:1,positional:1,mana:1,supportAmplification:1}[s]||1;if(s==='crit'&&/adrenaline|keen blunt/.test(t))return v+0.35;if(s==='critDamage'&&/keen blunt|burst/.test(t))return v+0.30;if(s==='attackSpeed'&&/raid captain|mass increase|wardancer|striker/.test(t))return v+0.30;if(s==='positional'&&/ambush master|master brawler|deathblade|reaper|scrapper/.test(t))return v+0.35;if(s==='mana'&&/summoner|mp|mana|max mp/.test(t))return v+0.35;if(s==='supportAmplification'&&/burst|grudge|adrenaline|keen blunt/.test(t))return v+0.15;if(/summoner/.test(x)&&s==='mana')return 1.45;return v}
function effects(c){return identity(c).role==='Support'?supportEffects(c):classTraits(c)}
function score(p){if(p.length!==4)return 0;const supports=p.filter(c=>identity(c).role==='Support');if(supports.length!==1)return 0;const dps=p.filter(c=>identity(c).role==='DPS');let base=p.reduce((n,c)=>n+identity(c).cp,0);if(!base)return 0;let mult=1;
for(const src of dps){for(const [s,w] of Object.entries(effects(src))){if(!w)continue;const targets=dps.filter(x=>x!==src);const avg=targets.length?targets.reduce((n,x)=>n+sensitivity(x,s),0)/targets.length:1;mult*=1+w*avg}}
const sup=supports[0];for(const [s,w] of Object.entries(supportEffects(sup))){const avg=dps.length?dps.reduce((n,x)=>n+sensitivity(x,s),0)/dps.length:1;mult*=1+w*avg}
const build=dps.reduce((n,c)=>{const m=buildMetrics(c);return n+((m.arkGrid+m.gems+m.engravings)/100000)},0);return base*mult*(1+Math.min(.025,build))}
function resolve(a){const m=new Map(chars().map(c=>[c.id,c])),p1=[],p2=[],used=new Set();for(const id of a.party1||[]){if(m.has(id)&&!used.has(id)&&p1.length<4){p1.push(m.get(id));used.add(id)}}for(const id of a.party2||[]){if(m.has(id)&&!used.has(id)&&p2.length<4){p2.push(m.get(id));used.add(id)}}for(const c of m.values())if(!used.has(c.id)){if(p1.length<4){p1.push(c);used.add(c.id)}else if(p2.length<4){p2.push(c);used.add(c.id)}}return{p1,p2}}
function syn(p){const out=[];for(const c of p){for(const k of Object.keys(effects(c))){const s=k==='supportAmplification'?'support amplification':k;if(!out.includes(s))out.push(s)}}return out}
function member(c){const x=identity(c);const col=x.role==='DPS'?'#e07a7a':'#79c98b';return `<div class="party-member authoritative-member" draggable="true" data-character-id="${esc(c.id)}"><a class="party-character-link" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${esc(x.name)}</a><span class="party-class-label">${esc(x.cls)}</span><span class="party-role-label" style="color:${col} !important">${x.role}</span><span class="party-stat-label">iLvl ${x.il} · CP ${x.cp}</span></div>`}
function render(a,msg=''){const h=document.querySelector('#suggestedParties');if(!h)return;const {p1,p2}=resolve(a),box=(n,k,p)=>`<article class="party authoritative-party" data-party="${k}"><div class="party-heading"><div><h3>${n}</h3><div class="party-score">Estimated potential: <strong>${fmt(score(p))}</strong></div></div><div class="party-meta">${p.length}/4 · ${p.filter(c=>identity(c).role==='Support').length} support</div></div><div class="party-dropzone authoritative-dropzone" data-drop-party="${k}">${p.map(member).join('')}</div><div class="party-synergies"><strong>Synergies:</strong> ${syn(p).join(', ')||'None'}</div></article>`;h.innerHTML=`<div class="authoritative-summary"><strong>Combined estimated potential: ${fmt(score(p1)+score(p2))}</strong><span> — Build-aware individual power with character-specific party synergy interactions.</span></div>${box('Party 1','party1',p1)}${box('Party 2','party2',p2)}${msg}`}
function combinations(a,k){const out=[];function r(i,p){if(p.length===k){out.push(p.slice());return}for(let j=i;j<=a.length-(k-p.length);j++)r(j+1,p.concat(a[j]))}r(0,[]);return out}
async function enrich(){const s=state();let changed=false;for(const c of s.characters||[]){if(!c.profile)continue;try{const r=await fetch(`${CONNECTOR}?url=${encodeURIComponent(c.url)}`,{cache:'no-store'});const d=await r.json();const text=norm(d.html||d.characterHtml||d.content||'');c.profile.optimizerBuild={text};changed=true}catch{}}if(changed)localStorage.setItem(STORAGE,JSON.stringify(s));return s}
async function optimize(){const b=document.querySelector('#optimizeBtn'),list=chars();if(list.length<8){render(assignments(),'<div class="optimizer-result">Add at least 8 characters to optimize parties.</div>');return}if(b){b.disabled=true;b.textContent='Optimizing…'}try{await enrich();const fresh=chars(),pools=fresh.length>14?[fresh.slice().sort((a,c)=>identity(c).cp-identity(a).cp).slice(0,12)]:combinations(fresh,8);let best=null,high=-Infinity;for(const eight of pools)for(const p1 of combinations(eight,4)){const p2=eight.filter(c=>!p1.includes(c));if(p1.filter(c=>identity(c).role==='Support').length!==1||p2.filter(c=>identity(c).role==='Support').length!==1)continue;const s=score(p1)+score(p2);if(s>high){high=s;best={party1:p1.map(c=>c.id),party2:p2.map(c=>c.id)}}}if(!best)throw Error('No valid 4/4 arrangement with one support per party.');save(best);render(best,`<div class="optimizer-result"><strong>Optimization complete.</strong> Best build-aware 8-character arrangement: <strong>${fmt(high)}</strong>.</div>`)}catch(e){console.error(e);render(assignments(),'<div class="optimizer-result">Optimization failed. Current parties preserved.</div>')}finally{if(b){b.disabled=false;b.textContent='Optimize Parties'}}}
function wire(h){h.addEventListener('dragstart',e=>{const m=e.target.closest('.party-member');if(m)e.dataTransfer.setData('text/plain',m.dataset.characterId)});h.addEventListener('dragover',e=>{if(e.target.closest('.party-dropzone'))e.preventDefault()});h.addEventListener('drop',e=>{const z=e.target.closest('.party-dropzone');if(!z)return;e.preventDefault();const id=e.dataTransfer.getData('text/plain'),a=assignments(),from=a.party1.includes(id)?'party1':a.party2.includes(id)?'party2':null,to=z.dataset.dropParty;if(!from)return;const target=e.target.closest('.party-member');if(target&&target.dataset.characterId!==id){const other=target.dataset.characterId,of=a.party1.includes(other)?'party1':a.party2.includes(other)?'party2':null;if(!of||of===from)return;const i=a[from].indexOf(id),j=a[of].indexOf(other);a[from][i]=other;a[of][j]=id}else if(to!==from&&a[to].length<4){a[from]=a[from].filter(x=>x!==id);a[to].push(id)}else return;const old=resolve(assignments()),before=score(old.p1)+score(old.p2);save(a);const now=resolve(a),after=score(now.p1)+score(now.p2),delta=before?((after-before)/before)*100:0;render(a,`<div class="swap-impact ${delta>=0?'positive':'negative'}"><span class="swap-impact-number">${pct(delta)} combined estimated potential damage.</span></div>`)})}
function start(){const h=document.querySelector('#suggestedParties'),b=document.querySelector('#optimizeBtn');if(!h||!b||h.dataset.optimizerV8)return;h.dataset.optimizerV8='1';b.addEventListener('click',optimize);wire(h);render(assignments())}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();})();