/* Lost Ark Party — build-aware, roster-independent optimizer v6 */
(()=>{
const STORAGE='lostark-hideout-private-v3';
const PARTY='lostark-hideout-party-assignments-v2';
const CONNECTOR='https://lostark-bible-connector.seraph0226.workers.dev/character';
const SUPPORTS=new Set(['Bard','Artist','Paladin','Valkyrie']);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
const fmt=n=>Math.round(n).toLocaleString();
function state(){try{return JSON.parse(localStorage.getItem(STORAGE)||'null')||{characters:[]}}catch{return{characters:[]}}}
function save(s){localStorage.setItem(STORAGE,JSON.stringify(s))}
function assignments(){try{return JSON.parse(localStorage.getItem(PARTY)||'null')||{party1:[],party2:[]}}catch{return{party1:[],party2:[]}}}
function saveAssignments(a){localStorage.setItem(PARTY,JSON.stringify(a))}
function text(doc){return(doc.body?.textContent||'').replace(/\r/g,'').split(/\n+/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean)}
function section(lines,start,stop){const out=[];for(let i=start;i<lines.length;i++){if(i!==start&&stop.some(x=>x.test(lines[i])))break;out.push(lines[i])}return out}
function num(s){const m=String(s||'').replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):null}
function parseBuild(html,profile){const doc=new DOMParser().parseFromString(html,'text/html'),lines=text(doc),all=lines.join(' | '),low=all.toLowerCase();
 const ark=lines.findIndex(x=>/^Ark Grid$/i.test(x)); const engr=lines.findIndex(x=>/^Engravings$/i.test(x)); const ap=lines.findIndex(x=>/^Ark Passive$/i.test(x)); const skills=lines.findIndex(x=>/^Skills$/i.test(x));
 const gridLines=ark>=0?section(lines,ark+1,[/^Cards$/i,/^Combat Power$/i,/^Ark Passive \+?/i]):[];
 const cores=[]; for(let i=0;i<gridLines.length;i++){const m=gridLines[i].match(/^(.+?)\s*$/); if(m&&i+1<gridLines.length&&/\bPoints\b/i.test(gridLines[i+1])){const p=num(gridLines[i+1]);if(p!=null)cores.push({name:m[1],points:p,type:/Order\s+(Sun|Moon|Star)/i.test(gridLines[i+2]||'')?'Order':/Chaos\s+(Sun|Moon|Star)/i.test(gridLines[i+2]||'')?'Chaos':'Unknown',theme:(gridLines[i+2]||'').match(/(?:Order|Chaos)\s+(Sun|Moon|Star)/i)?.[1]||null})}}
 const engrLines=engr>=0?section(lines,engr+1,[/^Ark Passive$/i,/^Ark Grid$/i,/^Skills$/i]).filter(x=>!/^(\d+\/\d+|Lv\.\d+)$/i.test(x)):[];
 const engravings=[]; for(const l of engrLines){if(/\b20\/20\b|\bLv\.\d+\b/i.test(l)&&l.length<80&&!/^Stone$|^Bracelet$/i.test(l))engravings.push(l.replace(/\s+\d+\/\d+.*$/,''))}
 const apLines=ap>=0?section(lines,ap+1,[/^Paradise$/i,/^Skills$/i]).filter(x=>!/^Evolution$|^Enlightenment$|^Leap$/i.test(x)&&!/^\+?\d/.test(x)):[];
 const stats={crit:0,specialization:0,swiftness:0}; for(const l of lines){let m=l.match(/^Crit Lv\.\s*(\d+)/i);if(m)stats.crit=Number(m[1]);m=l.match(/^Specialization Lv\.\s*(\d+)/i);if(m)stats.specialization=Number(m[1]);m=l.match(/^Swiftness Lv\.\s*(\d+)/i);if(m)stats.swiftness=Number(m[1])}
 const skillLines=skills>=0?lines.slice(skills+1):[]; const skillNames=[]; for(let i=0;i<skillLines.length;i++){if(/^Lv\.\s*\d+/i.test(skillLines[i])&&skillLines[i+1]&&!/^Lv\./i.test(skillLines[i+1]))skillNames.push(skillLines[i+1])}
 const coreText=cores.map(x=>x.name).join(' | ').toLowerCase();
 const build={cores,arkPassive:apLines,engravings:[...new Set(engravings)],stats,skills:[...new Set(skillNames)],rawMarkers:{hasArkGrid:ark>=0,hasArkPassive:ap>=0},traits:{critSensitive:false,critDamageSensitive:false,attackSpeedSensitive:false,positional:false,manaSensitive:false,cooldownSensitive:false,burst:false,summon:false,frontAttack:false,backAttack:false,partyAmplification:false}};
 const t=build.traits;
 t.critSensitive=/crit|critical|keen blunt|adrenaline/.test(low)||stats.crit>=8;
 t.critDamageSensitive=/crit damage|crit hit damage|keen blunt|pulverize|critical/i.test(low);
 t.attackSpeedSensitive=/attack speed|swiftness|raid captain|mass increase|standing striker|rapid|speed/i.test(low)||stats.swiftness>=15;
 t.positional=/ambush master|back attack|head attack|frontal|master brawler|positional/i.test(low);
 t.manaSensitive=/mana|max mp|mp recovery|mp regen/i.test(low);
 t.cooldownSensitive=/cooldown|quick recharge|skill cooldown/i.test(low)||stats.swiftness>=15;
 t.burst=/burst|first blood|punisher|surge|deathblow|striker|critical/i.test(coreText+' '+apLines.join(' ').toLowerCase());
 t.summon=/summon|elemental|command awakening|entwinement/i.test(coreText+' '+apLines.join(' ').toLowerCase())||norm(profile?.class)==='summoner';
 t.frontAttack=/frontal|head attack|master brawler/i.test(low);
 t.backAttack=/back attack|ambush master/i.test(low);
 t.partyAmplification=/ally damage|ally atk|support amplification|party members/i.test(low);
 return {...build,loadout:profile?.loadout||'Unknown',sourceUrl:profile?.sourceUrl||''}
}
async function enrich(c){const p=c.profile||{};if(p.optimizerBuild&&p.optimizerBuild.sourceUrl===c.url)return p;try{const r=await fetch(`${CONNECTOR}?url=${encodeURIComponent(c.url)}`,{cache:'no-store',headers:{Accept:'application/json'}});const d=await r.json();if(!r.ok||d.ok===false)throw Error(d.error||'Bible fetch failed');const build=parseBuild(d.html||d.characterHtml||d.content||d.page,p);p.optimizerBuild={...build,sourceUrl:c.url,retrievedAt:new Date().toISOString()};c.profile=p;return p}catch(e){return p}}
const classSynergy={
 Berserker:['damage'],Destroyer:['damage'],Gunlancer:['damage','positional'],Slayer:['damage'],Summoner:['damage'],Sorceress:['damage'],Sharpshooter:['damage'],Artillerist:['damage'],Scrapper:['damage'],Shadowhunter:['damage'],Reaper:['damage'],Souleater:['damage'],'Soul Eater':['damage'],Breaker:['damage'],Machinist:['damage'],Soulfist:['attackPower'],Wardancer:['crit','attackSpeed'],Striker:['crit','attackSpeed'],Glaivier:['crit','critDamage'],Glavier:['crit','critDamage'],Deathblade:['positional','attackSpeed'],Gunslinger:['crit'],Deadeye:['crit'],Arcanist:['crit'],Arcana:['crit'],Aeromancer:['crit'],Bard:['supportAmplification','attackSpeed'],Artist:['supportAmplification','mana'],Paladin:['supportAmplification'],Valkyrie:['supportAmplification']
};
const baseWeight={damage:.010,crit:.010,critDamage:.008,attackPower:.007,attackSpeed:.005,positional:.008,mana:.002,supportAmplification:.045};
function ident(c){const p=c.profile||{};let cls=p.class||'Unknown';if(norm(p.name||c.name)==='diamarte')cls='Souleater';return{name:p.name||c.name||'',class:cls,role:SUPPORTS.has(cls)?'Support':(p.role==='Support'?'Support':'DPS'),cp:Number(p.cp)||0,ilvl:Number(p.ilvl)||0,build:p.optimizerBuild||{traits:{}}}}
function affinity(c,s){const t=ident(c).build.traits||{},cl=ident(c).class;let a=1;if(s==='crit'){if(t.critSensitive)a*=1.35;if(cl==='Summoner')a*=1.1}if(s==='critDamage'&&t.critDamageSensitive)a*=1.3;if(s==='attackSpeed'&&t.attackSpeedSensitive)a*=1.2;if(s==='positional'&&t.positional)a*=1.35;if(s==='mana'&&t.manaSensitive)a*=1.3;if(s==='attackPower')a*=1.05;if(s==='damage'){if(t.burst)a*=1.15;if(t.summon)a*=1.05}return a}
function synergyFor(c){return classSynergy[ident(c).class]||['damage']}
function scoreParty(p){if(p.length!==4)return 0;const ids=p.map(c=>c.id);if(new Set(ids).size!==4)return 0;const su=p.filter(c=>ident(c).role==='Support');if(su.length!==1)return 0;let score=p.reduce((n,c)=>n+ident(c).cp,0);let mult=1;const seen=new Set();for(const src of p){for(const s of synergyFor(src)){if(s==='supportAmplification'){if(!seen.has('supportAmplification')){mult*=1+baseWeight[s];seen.add(s)}continue}const targets=p.filter(x=>x!==src&&ident(x).role!=='Support');if(!targets.length)continue;const key=`${ident(src).class}:${s}`;if(seen.has(key))continue;seen.add(key);const avg=targets.reduce((n,x)=>n+affinity(x,s),0)/targets.length;mult*=1+(baseWeight[s]||0)*avg}}for(const c of p){const t=ident(c).build.traits||{};if(t.partyAmplification)mult*=1.002}return score*mult}
function allComb(arr,k,start=0,p=[],out=[]){if(p.length===k){out.push(p);return out}for(let i=start;i<=arr.length-(k-p.length);i++)allComb(arr,k,i+1,p.concat(arr[i]),out);return out}
function renderParties(a,impact=''){const chars=state().characters.filter(c=>c.profile),map=new Map(chars.map(c=>[c.id,c])),p1=(a.party1||[]).map(id=>map.get(id)).filter(Boolean),p2=(a.party2||[]).map(id=>map.get(id)).filter(Boolean),total=scoreParty(p1)+scoreParty(p2);const card=c=>{const x=ident(c),color=x.role==='DPS'?'#e07a7a':'#79c98b';return `<div class="party-member authoritative-member" draggable="true" data-character-id="${esc(c.id)}"><div class="party-member-main"><a class="party-character-link" href="${esc(c.url)}" target="_blank" rel="noopener noreferrer">${esc(x.name)}</a><span class="party-class-label">${esc(x.class)}</span><span class="party-role-label" style="color:${color}!important">${x.role}</span><span class="party-stat-label">iLvl ${x.ilvl.toLocaleString(undefined,{maximumFractionDigits:2})} · CP ${x.cp.toLocaleString(undefined,{maximumFractionDigits:2})}</span></div></div>`};const syn=p=>[...new Set(p.flatMap(synergyFor).filter(x=>x!=='supportAmplification'))].concat(p.some(c=>synergyFor(c).includes('supportAmplification'))?['support amplification']:[]);const party=(name,id,p)=>`<article class="party authoritative-party" data-party="${id}"><div class="party-heading"><div><h3>${name}</h3><div class="party-score">Estimated potential: <strong>${fmt(scoreParty(p))}</strong></div></div><div class="party-meta">${p.length}/4 · ${p.filter(c=>ident(c).role==='Support').length} support</div></div><div class="party-dropzone authoritative-dropzone" data-drop-party="${id}">${p.map(card).join('')||'<div class="party-empty">Drop a character here</div>'}</div><div class="party-synergies"><strong>Synergies:</strong> ${syn(p).map(esc).join(', ')||'None'}</div></article>`;document.querySelector('#suggestedParties').innerHTML=`<div class="authoritative-summary"><strong>Combined estimated potential: ${fmt(total)}</strong><span class="potential-explanation"> — CP-based individual power with build-aware party synergy interactions. Higher is better; not a literal in-game DPS value.</span></div><div class="authoritative-parties">${party('Party 1','party1',p1)}${party('Party 2','party2',p2)}</div>${impact}`}
function wireDrag(){const host=document.querySelector('#suggestedParties');if(!host)return;host.addEventListener('dragstart',e=>{const m=e.target.closest('.party-member');if(m)e.dataTransfer.setData('text/plain',m.dataset.characterId)});host.addEventListener('dragover',e=>{if(e.target.closest('.party-dropzone'))e.preventDefault()});host.addEventListener('drop',e=>{const z=e.target.closest('.party-dropzone');if(!z)return;e.preventDefault();const id=e.dataTransfer.getData('text/plain'),target=e.target.closest('.party-member');const a=assignments(),from=a.party1.includes(id)?'party1':a.party2.includes(id)?'party2':null;if(!from)return;const before=scoreParty((a.party1||[]).map(x=>state().characters.find(c=>c.id===x)).filter(Boolean))+scoreParty((a.party2||[]).map(x=>state().characters.find(c=>c.id===x)).filter(Boolean));if(target&&target.dataset.characterId!==id){const other=target.dataset.characterId,op=a.party1.includes(other)?'party1':'party2';const i=a[from].indexOf(id),j=a[op].indexOf(other);if(from!==op){a[from][i]=other;a[op][j]=id}}else if(from!==z.dataset.dropParty&&a[z.dataset.dropParty].length<4){a[from]=a[from].filter(x=>x!==id);a[z.dataset.dropParty].push(id)}saveAssignments(a);const after=scoreParty((a.party1||[]).map(x=>state().characters.find(c=>c.id===x)).filter(Boolean))+scoreParty((a.party2||[]).map(x=>state().characters.find(c=>c.id===x)).filter(Boolean));const pct=before?((after-before)/before)*100:0;renderParties(a,`<div class="swap-impact ${pct>=0?'positive':'negative'}">${pct>=0?'+':''}${pct.toFixed(2)}% combined estimated potential damage.</div>`)})}
async function optimize(){const s=state(),chars=s.characters.filter(c=>c.profile);if(chars.length<8){renderParties(assignments());return}const btn=document.querySelector('#optimizeBtn');if(btn)btn.disabled=true;try{for(const c of chars)await enrich(c);save(s);const roster=chars;let best=null,bestScore=-Infinity;const eights=roster.length<=14?allComb(roster,8):[roster.slice().sort((a,b)=>(b.profile.cp||0)-(a.profile.cp||0)).slice(0,8)];for(const eight of eights){for(const p1 of allComb(eight,4)){const p2=eight.filter(c=>!p1.includes(c));if(p1.filter(c=>ident(c).role==='Support').length!==1||p2.filter(c=>ident(c).role==='Support').length!==1)continue;const sc=scoreParty(p1)+scoreParty(p2);if(sc>bestScore){bestScore=sc;best={party1:p1.map(c=>c.id),party2:p2.map(c=>c.id)}}}}if(best){saveAssignments(best);renderParties(best,`<div class="optimizer-result"><strong>Optimization complete.</strong> Best valid 8-character arrangement: <strong>${fmt(bestScore)}</strong>.</div>`)} }finally{if(btn)btn.disabled=false}}
function start(){const btn=document.querySelector('#optimizeBtn'),host=document.querySelector('#suggestedParties');if(!btn||!host)return;const fresh=btn.cloneNode(true);btn.replaceWith(fresh);fresh.addEventListener('click',optimize);wireDrag();const a=assignments();if((a.party1||[]).length||(a.party2||[]).length)renderParties(a)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else setTimeout(start,50);
})();
