/* Lost Ark Hideout — optimizer v17: Bible-derived support uptime medians */
(()=>{
'use strict';
const STORE='lostark-hideout-private-v3',PARTY='lostark-hideout-party-assignments-v2',SUPPORTS=new Set(['Bard','Artist','Paladin','Valkyrie']);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=v=>Number.isFinite(Number(v))?Number(v):0,fmt=v=>Math.round(num(v)).toLocaleString(),pct=v=>`${v>=0?'+':''}${v.toFixed(2)}%`,clean=s=>String(s??'').replace(/\s+/g,' ').trim();
function load(){try{return JSON.parse(localStorage.getItem(STORE)||'null')||{characters:[]}}catch{return{characters:[]}}}
function roster(){return(load().characters||[]).filter(c=>c&&c.id)}
function partyState(){try{const a=JSON.parse(localStorage.getItem(PARTY)||'null');if(a&&Array.isArray(a.party1)&&Array.isArray(a.party2))return a}catch{}return{party1:[],party2:[]}}
const save=a=>localStorage.setItem(PARTY,JSON.stringify(a));
const profile=c=>c.profile||c.data||{};
function field(p,...keys){for(const k of keys)if(p&&p[k]!=null)return p[k];return ''}
function build(c){try{return window.LostArkBuildProfilesAuthorityV1?.get(c.url)||window.LostArkBuildProfilesV2?.get(c.url)||window.LostArkBuildProfilesV3?.get(c.url)||{}}catch{return{}}}
function info(c){const p=profile(c),b=build(c),name=clean(field(p,'name','characterName'))||clean(c.name)||'Unknown',cls=clean(field(p,'class','className','characterClass'))||clean(b.className)||'Unknown',role=field(p,'role')||(SUPPORTS.has(cls)?'Support':'DPS');return{name,cls,role:role==='Support'||SUPPORTS.has(cls)?'Support':'DPS',cp:num(field(p,'cp','combatPower')),ilvl:num(field(p,'ilvl','itemLevel')),url:c.url||field(p,'url','profileUrl')||'',build:b}}
function text(c){const p=profile(c),b=build(c);return clean([p.rawText,p.text,p.characterText,p.arkGridText,p.arkPassiveText,p.engravingsText,p.gemsText,b.text,b.engravings?.join(' '),b.grid?.map(x=>x.name).join(' '),b.arkPassive?.map(x=>x.name).join(' ')].filter(Boolean).join(' ')).toLowerCase()}
function positional(c){const b=build(c),t=text(c);if(b.positional&&b.positional!=='Unknown')return b.positional;if(/ambush master|back attack/.test(t))return'Back Attack';if(/master brawler|front attack/.test(t))return'Front Attack';if(/hit master/.test(t))return'Hit Master';return'Unknown'}
function flags(c){const t=text(c),b=build(c);return{summoner:/summoner|서머너/.test(t)||info(c).cls==='Summoner',keenBlunt:/keen blunt weapon|keen blunt/.test(t),adrenaline:/adrenaline/.test(t),raidCaptain:/raid captain/.test(t),swiftness:/swiftness/.test(t),mana:/mana|mp recovery|boundless/.test(t),burst:!!b.burst||/igniter|full moon|punisher|burst/.test(t)}}
const SYN={damage:{classes:['Berserker','Shadowhunter','Scrapper','Sorceress','Sharpshooter','Summoner','Destroyer','Artillerist','Reaper','Slayer','Souleater','Soul Eater','Breaker','Gunlancer'],value:.06},crit:{classes:['Arcanist','Arcana','Deadeye','Gunslinger','Wardancer','Striker','Aeromancer','Glaivier','Glavier'],value:.10},critDamage:{classes:['Glaivier','Glavier'],value:.08},attackSpeed:{classes:['Wardancer','Striker','Deathblade','Gunlancer'],value:.08},attackPower:{classes:['Soulfist','Machinist','Scouter'],value:.06},positional:{classes:['Deathblade','Gunlancer'],value:.04},mana:{classes:['Summoner'],value:.08}};
const classMatch=(cls,list)=>{const x=String(cls).toLowerCase().replace(/\s+/g,'');return list.some(v=>x===v.toLowerCase().replace(/\s+/g,''))};
function provided(c){const i=info(c),out=[];for(const[k,v]of Object.entries(SYN))if(classMatch(i.cls,v.classes))out.push({type:k,value:v.value});return out}
function recipientWeight(c,type){const f=flags(c),i=info(c);if(i.role!=='DPS')return 0;let w=1;if(type==='crit'){if(f.keenBlunt||f.adrenaline||f.burst)w+=.35;if(/100.?% crit|full crit/.test(text(c)))w-=.30}if(type==='critDamage'&&(f.keenBlunt||f.burst))w+=.30;if(type==='attackSpeed'&&(f.raidCaptain||f.swiftness))w+=.35;if(type==='positional'){const p=positional(c);w=p==='Back Attack'||p==='Front Attack'?1.35:p==='Hit Master'?.55:.85}if(type==='attackPower'&&(f.burst||f.adrenaline))w+=.12;if(type==='mana')w=f.summoner||f.mana?1.55:.20;if(type==='damage'&&f.summoner)w+=.10;return Math.max(0,w)}
function supportEffects(c){const cls=info(c).cls.toLowerCase();if(cls==='artist')return[{type:'supportAmplification',value:.10,uptime:'identity'},{type:'mana',value:.08,uptime:null},{type:'attackSpeed',value:.04,uptime:'ha'}];if(cls==='bard')return[{type:'supportAmplification',value:.10,uptime:'identity'},{type:'attackPower',value:.06,uptime:'ap'},{type:'attackSpeed',value:.035,uptime:'ha'},{type:'mana',value:.12,uptime:null}];if(cls==='paladin')return[{type:'supportAmplification',value:.10,uptime:'identity'},{type:'damage',value:.03,uptime:'brand'}];if(cls==='valkyrie')return[{type:'supportAmplification',value:.095,uptime:'identity'},{type:'attackSpeed',value:.06,uptime:'ha'}];return[{type:'supportAmplification',value:.09,uptime:'identity'}]}
function supportUptime(p,target,effect='identity'){const sup=p.find(c=>info(c).role==='Support');if(!sup)return 0;const dynamic=window.LostArkSupportStats?.get(info(sup).cls,effect);if(Number.isFinite(dynamic))return dynamic;const sc=info(sup).cls,known=[...new Set(p.filter(c=>info(c).role==='DPS').map(positional).filter(x=>x!=='Unknown'))],front=known.includes('Front Attack'),back=known.includes('Back Attack'),hm=known.includes('Hit Master');let u;if(sc==='Paladin'||sc==='Valkyrie')u=known.length>=3?.94:front&&back?.96:.99;else u=known.length>=3?.72:front&&back?.76:hm&&(front||back)?.84:.95;const tp=positional(target);if((sc==='Bard'||sc==='Artist')&&tp==='Hit Master'&&known.length>=2)u-=.05;if((sc==='Bard'||sc==='Artist')&&tp!=='Unknown'&&known.length===1)u+=.02;return Math.max(.60,Math.min(1,u))}
function supportSummary(c){return window.LostArkSupportStats?.summary?.(info(c).cls)||null}
function contribution(p,target){if(info(target).role!=='DPS')return{base:0,synergy:0,support:0,total:0,details:[]};const cp=info(target).cp,base=cp;let synergy=0,support=0,details=[];for(const src of p.filter(c=>c!==target&&info(c).role==='DPS'))for(const s of provided(src)){const value=cp*s.value*recipientWeight(target,s.type);synergy+=value;details.push({source:info(src).name,type:s.type,value})}const sup=p.find(c=>info(c).role==='Support');if(sup){for(const e of supportEffects(sup)){const uptime=e.uptime===null?1:supportUptime(p,target,e.uptime);const value=cp*e.value*recipientWeight(target,e.type)*uptime;support+=value;details.push({source:info(sup).name,type:e.type,value,uptime})}}return{base,synergy,support,total:base+synergy+support,details,uptime:sup?supportUptime(p,target,'identity'):0,supportSummary:sup?supportSummary(sup):null}}
function breakdown(p){const dps=p.filter(c=>info(c).role==='DPS'),sup=p.filter(c=>info(c).role==='Support');if(p.length!==4||sup.length!==1)return{total:0,base:0,synergy:0,support:0,contributions:[],coherence:0};const contributions=dps.map(c=>({c,...contribution(p,c)}));return{total:contributions.reduce((n,x)=>n+x.total,0),base:contributions.reduce((n,x)=>n+x.base,0),synergy:contributions.reduce((n,x)=>n+x.synergy,0),support:contributions.reduce((n,x)=>n+x.support,0),contributions,coherence:Math.round(contributions.reduce((n,x)=>n+x.uptime,0)/dps.length*100)}}
const partyScore=party=>breakdown(party).total;
function resolve(a){const m=new Map(roster().map(c=>[c.id,c])),p1=[],p2=[],used=new Set();for(const id of a.party1||[])if(m.has(id)&&p1.length<4&&!used.has(id)){p1.push(m.get(id));used.add(id)}for(const id of a.party2||[])if(m.has(id)&&p2.length<4&&!used.has(id)){p2.push(m.get(id));used.add(id)}for(const c of m.values())if(!used.has(c.id)){if(p1.length<4)p1.push(c),used.add(c.id);else if(p2.length<4)p2.push(c),used.add(c.id)}return{p1,p2}}
function synergyLabels(p){const out=[];for(const c of p)for(const s of provided(c))if(!out.includes(s.type))out.push(s.type);if(p.some(c=>info(c).role==='Support')&&!out.includes('support amplification'))out.push('support amplification');if(p.some(c=>flags(c).summoner)&&!out.includes('mana'))out.push('mana');return out.map(x=>x==='supportAmplification'?'support amplification':x)}
const DEFINITIONS={'Base DPS Power':'Current combat power of the DPS characters. This is the starting point for party scoring.','Party Synergy':'Current-value contribution from effects supplied by the other DPS characters, adjusted for whether the recipient can benefit from the effect.','Support Impact':'Current-value contribution from the support. Relevant support effects use the selected encounter’s observed median uptime data from Lost Ark Bible; other party compatibility factors remain separate.','Upgrade Potential':'Informational only. Detectable upgrade opportunities are shown separately from current power and never affect party optimization scores.'};
function tip(label,value){return `<span class="optimizer-definition-trigger"><span class="optimizer-definition-label">${label}</span><span class="optimizer-definition">${value}</span></span>`}
function changeMark(delta,type='number'){if(Math.abs(delta)<.0001)return '';const up=delta>0;return `<span class="metric-change ${up?'metric-up':'metric-down'}">${up?'▲':'▼'} ${type==='pct'?Math.abs(delta).toFixed(2)+' pts':Math.abs(delta)<1?Math.abs(delta).toFixed(2):fmt(Math.abs(delta))}</span>`}
function metric(label,value,definition,diff,type='number'){return `<div class="party-metric">${tip(label,definition)} <strong>${value}</strong>${changeMark(diff,type)}</div>`}
function upgradeHtml(c){try{const x=window.LostArkUpgradePotentialV1?.forCharacter?.(c);if(x?.html)return x.html}catch{}return '<strong>Upgrade Potential</strong><div class="upgrade-potential-note">No defensible upgrade opportunities are currently detectable from the available Bible data.</div>'}
function uptimeHtml(summary,enc){if(!summary)return '<div>Observed median support uptime is unavailable for this encounter.</div>';const e=window.LostArkOptimizerMode?.encounter||{};return `<div><strong>Observed median support uptime</strong></div><div>${enc||e.label||'Selected encounter'}</div><div>AP: ${summary.ap!=null?(summary.ap*100).toFixed(2)+'%':'—'} · Brand: ${summary.brand!=null?(summary.brand*100).toFixed(2)+'%':'—'} · H.A. Skill: ${summary.ha!=null?(summary.ha*100).toFixed(2)+'%':'—'} · Identity: ${summary.identity!=null?(summary.identity*100).toFixed(2)+'%':'—'}</div>`}
function member(c,x){const i=info(c),color=i.role==='Support'?'#79c98b':'#e07a7a',details=x?.details?.map(d=>`<div class="chb-synergy"><strong>${esc(d.type)}</strong> from ${esc(d.source)}: ${fmt(d.value)}${d.uptime!==undefined?` · observed median ${(d.uptime*100).toFixed(2)}%`:''}</div>`).join('')||'',summary=x?.supportSummary;return `<div class="party-member authoritative-member" draggable="true" data-character-id="${esc(c.id)}"><a class="party-character-link" href="${esc(i.url)}" target="_blank" rel="noopener noreferrer">${esc(i.name)}</a><span class="party-class-label">${esc(i.cls)}</span><span class="party-role-label" style="color:${color}!important">${i.role}</span><span class="party-stat-label">${esc(positional(c))} · CP ${fmt(i.cp)}</span><div class="character-hover-breakdown"><div class="chb-head"><strong>${esc(i.name)}</strong><span>CP ${fmt(x?.base||i.cp)} · Contribution ${fmt(x?.total||0)}</span></div><div class="chb-stats"><span>Party Synergy +${((x?.synergy||0)/(x?.base||1)*100).toFixed(2)}%</span><span>Support Impact +${((x?.support||0)/(x?.base||1)*100).toFixed(2)}%</span>${i.role==='Support'?`<span>Observed median support uptime</span>`:`<span>Support compatibility uses encounter data</span>`}</div>${i.role==='Support'?`<div class="chb-detail">${uptimeHtml(summary)}</div>`:''}<div class="chb-upgrade">${upgradeHtml(c)}</div><div class="chb-detail">${details||'<div>No direct party effects detected.</div>'}</div></div></div>`}
function styles(){if(document.getElementById('optimizer-v17-style'))return;const s=document.createElement('style');s.id='optimizer-v17-style';s.textContent=`.combined-breakdown,.party-breakdown{display:flex!important;flex-wrap:wrap!important;gap:10px 28px!important;margin-top:12px!important;line-height:1.55!important}.combined-breakdown>span,.party-breakdown>.party-metric{white-space:nowrap!important}.party-metric{display:inline-flex!important;align-items:center!important;gap:7px!important;position:relative}.metric-change{font-size:12px;font-weight:700;white-space:nowrap}.metric-up{color:#65c878}.metric-down{color:#ef6b6b}.optimizer-definition-trigger{position:relative;display:inline-block}.optimizer-definition-label{border-bottom:1px dotted currentColor;cursor:help}.optimizer-definition{display:none;position:absolute;z-index:3000;left:0;bottom:calc(100% + 9px);width:310px;padding:11px 13px;border-radius:7px;background:#17191d;color:#eee;border:1px solid rgba(255,255,255,.18);box-shadow:0 8px 24px rgba(0,0,0,.4);font-size:12px;font-weight:400;line-height:1.55;text-align:left;white-space:normal}.optimizer-definition-trigger:hover>.optimizer-definition{display:block}.authoritative-member{position:relative}.character-hover-breakdown{position:absolute;z-index:3000;left:50%;bottom:calc(100% + 10px);transform:translateX(-50%);display:none;width:430px;padding:12px 14px;border-radius:8px;background:#17191d;color:#eee;border:1px solid rgba(255,255,255,.18);box-shadow:0 8px 24px rgba(0,0,0,.4);font-size:12px;line-height:1.5;text-align:left;pointer-events:none}.authoritative-member:hover>.character-hover-breakdown{display:block}.authoritative-member:hover{z-index:3001}.chb-head,.chb-stats{display:flex;justify-content:space-between;gap:10px}.chb-stats{justify-content:flex-start;flex-wrap:wrap;margin-top:6px}.chb-upgrade{margin-top:9px;padding-top:8px;border-top:1px solid rgba(255,255,255,.12)}.chb-detail{display:flex;flex-direction:column;gap:5px;margin-top:9px;color:#bbb}.chb-synergy{display:block;padding:2px 0;line-height:1.45}.upgrade-potential-row{display:flex;justify-content:space-between;gap:14px;padding:4px 0;border-bottom:1px solid rgba(255,255,255,.07)}.upgrade-potential-total{display:flex;justify-content:space-between;gap:12px;margin-top:8px;padding-top:7px;border-top:1px solid rgba(255,255,255,.15)}`;document.head.appendChild(s)}
function diffBreakdown(before,after){const bp=before.base||0,ap=after.base||0;return{base:ap-bp,synergyPct:(ap?after.synergy/ap*100:0)-(bp?before.synergy/bp*100:0),supportPct:(ap?after.support/ap*100:0)-(bp?before.support/bp*100:0),total:after.total-before.total,totalPct:before.total?((after.total-before.total)/before.total)*100:0}}
function render(a,extra='',diffs={}){styles();const h=document.querySelector('#suggestedParties');if(!h)return;const{p1,p2}=resolve(a),b1=breakdown(p1),b2=breakdown(p2),base=b1.base+b2.base,total=b1.total+b2.total,cd=diffs.combined||{};const box=(n,k,p,b)=>`<article class="party authoritative-party" data-party="${k}"><div class="party-heading"><div><h3>${n}</h3><div class="party-score">Estimated potential: <strong>${fmt(b.total)}</strong>${changeMark(diffs[k]?.total||0)} ${diffs[k]?.totalPct?`(${pct(diffs[k].totalPct)})`:''}</div></div><div class="party-meta">${p.length}/4 · ${p.filter(c=>info(c).role==='Support').length} support</div></div><div class="party-dropzone authoritative-dropzone" data-drop-party="${k}">${p.map(c=>member(c,b.contributions.find(x=>x.c===c))).join('')}</div><div class="party-synergies"><strong>Synergies:</strong> ${synergyLabels(p).join(', ')||'None'} · Observed median support uptime data${b.coherence?` · identity median ${b.coherence}%`:''}</div><div class="party-breakdown">${metric('Base DPS Power',fmt(b.base),DEFINITIONS['Base DPS Power'],diffs[k]?.base||0)}${metric('Party Synergy','+'+(b.base?b.synergy/b.base*100:0).toFixed(2)+'%',DEFINITIONS['Party Synergy'],diffs[k]?.synergyPct||0,'pct')}${metric('Support Impact','+'+(b.base?b.support/b.base*100:0).toFixed(2)+'%',DEFINITIONS['Support Impact'],diffs[k]?.supportPct||0,'pct')}${metric('Upgrade Potential','Informational',DEFINITIONS['Upgrade Potential'])}</div></article>`;h.innerHTML=`<div class="authoritative-summary"><strong>Combined estimated potential: ${fmt(total)}</strong>${cd.total?` ${changeMark(cd.total)} (${pct(cd.totalPct)})`:''}<span> — Current character power, detected party synergies, and support compatibility using Bible-derived support uptime medians. Upgrade Potential is informational only.</span><div class="combined-breakdown"><span>${tip('Base DPS Power',DEFINITIONS['Base DPS Power'])} <strong>${fmt(base)}</strong>${changeMark(cd.base||0)}</span><span>${tip('Party Synergy',DEFINITIONS['Party Synergy'])} <strong>+${base?((b1.synergy+b2.synergy)/base*100).toFixed(2):'0.00'}%</strong>${changeMark(cd.synergyPct||0,'pct')}</span><span>${tip('Support Impact',DEFINITIONS['Support Impact'])} <strong>+${base?((b1.support+b2.support)/base*100).toFixed(2):'0.00'}%</strong>${changeMark(cd.supportPct||0,'pct')}</span><span>${tip('Upgrade Potential',DEFINITIONS['Upgrade Potential'])}</span></div></div>${box('Party 1','party1',p1,b1)}${box('Party 2','party2',p2,b2)}${extra}`}
function combos(a,k){const out=[];function rec(i,p){if(p.length===k){out.push(p.slice());return}for(let j=i;j<=a.length-(k-p.length);j++)rec(j+1,p.concat(a[j]))}rec(0,[]);return out}
const yieldFrame=()=>new Promise(r=>setTimeout(r,0));
async function optimize(){const list=roster(),b=document.querySelector('#optimizeBtn');if(list.length<8)return;if(b){b.disabled=true;b.textContent='Loading encounter data…';b.setAttribute('aria-busy','true')}await yieldFrame();try{if(window.LostArkSupportStats&&!window.LostArkOptimizerMode?.general)await window.LostArkSupportStats.ensure();if(b)b.textContent='Optimizing…';let best=null,high=-Infinity;const eight=list.slice(0,8);for(const p1 of combos(eight,4)){const p2=eight.filter(c=>!p1.includes(c));if(p1.filter(c=>info(c).role==='Support').length!==1||p2.filter(c=>info(c).role==='Support').length!==1)continue;const s=partyScore(p1)+partyScore(p2);if(s>high){high=s;best={party1:p1.map(c=>c.id),party2:p2.map(c=>c.id)}}await yieldFrame()}if(!best)throw Error('No valid arrangement with exactly one support per party.');save(best);render(best,`<div class="optimizer-result"><strong>Optimization complete.</strong> Best practical 8-character arrangement: <strong>${fmt(high)}</strong>. Bible support uptime medians were used where available; Upgrade Potential was not used.</div>`)}catch(e){console.error(e);render(partyState(),'<div class="optimizer-result">Optimization failed. Current parties preserved.</div>')}finally{if(b){b.disabled=false;b.textContent='Optimize Parties';b.removeAttribute('aria-busy')}}}
function wire(h){h.addEventListener('dragstart',e=>{const m=e.target.closest('.party-member');if(m)e.dataTransfer.setData('text/plain',m.dataset.characterId)});h.addEventListener('dragover',e=>{if(e.target.closest('.party-dropzone'))e.preventDefault()});h.addEventListener('drop',e=>{const z=e.target.closest('.party-dropzone');if(!z)return;e.preventDefault();const id=e.dataTransfer.getData('text/plain'),a=partyState(),from=a.party1.includes(id)?'party1':a.party2.includes(id)?'party2':null,to=z.dataset.dropParty;if(!from)return;const target=e.target.closest('.party-member');if(target&&target.dataset.characterId!==id){const other=target.dataset.characterId,of=a.party1.includes(other)?'party1':a.party2.includes(other)?'party2':null;if(!of||of===from)return;const old=resolve(a),before1=breakdown(old.p1),before2=breakdown(old.p2),beforeTotal=before1.total+before2.total,i=a[from].indexOf(id),j=a[of].indexOf(other);a[from][i]=other;a[of][j]=id;save(a);const now=resolve(a),after1=breakdown(now.p1),after2=breakdown(now.p2),afterTotal=after1.total+after2.total,diffs={party1:diffBreakdown(before1,after1),party2:diffBreakdown(before2,after2),combined:diffBreakdown({base:before1.base+before2.base,synergy:before1.synergy+before2.synergy,support:before1.support+before2.support,total:beforeTotal},{base:after1.base+after2.base,synergy:after1.synergy+after2.synergy,support:after1.support+after2.support,total:afterTotal})};render(a,'',diffs);return}if(to!==from&&a[to].length<4){const old=resolve(a),before1=breakdown(old.p1),before2=breakdown(old.p2),beforeTotal=before1.total+before2.total;a[from]=a[from].filter(x=>x!==id);a[to].push(id);save(a);const now=resolve(a),after1=breakdown(now.p1),after2=breakdown(now.p2),afterTotal=after1.total+after2.total,diffs={party1:diffBreakdown(before1,after1),party2:diffBreakdown(before2,after2),combined:diffBreakdown({base:before1.base+before2.base,synergy:before1.synergy+before2.synergy,support:before1.support+before2.support,total:beforeTotal},{base:after1.base+after2.base,synergy:after1.synergy+after2.synergy,support:after1.support+after2.support,total:afterTotal})};render(a,'',diffs)}})}
/* No click binding: General Optimization owns the button in general mode and the
   encounter optimizer owns it in Raid Specific mode. This handler has been
   unreachable since the general optimizer began cancelling the click, and
   re-enabling it would overwrite the encounter result. wire/render stay live. */
function start(){const h=document.querySelector('#suggestedParties'),b=document.querySelector('#optimizeBtn');if(!h||!b||h.dataset.optimizerV17)return;h.dataset.optimizerV17='1';wire(h);render(partyState())}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
