/* Lost Ark Hideout — optimizer v14 + hover definitions */
(()=>{
'use strict';
const STORE='lostark-hideout-private-v3',PARTY='lostark-hideout-party-assignments-v2';
const SUPPORTS=new Set(['Bard','Artist','Paladin','Valkyrie']);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number.isFinite(Number(v))?Number(v):0,fmt=v=>Math.round(num(v)).toLocaleString(),pct=v=>`${v>=0?'+':''}${v.toFixed(2)}%`,clean=s=>String(s??'').replace(/\s+/g,' ').trim();
function load(){try{return JSON.parse(localStorage.getItem(STORE)||'null')||{characters:[]}}catch{return{characters:[]}}}
function roster(){return(load().characters||[]).filter(c=>c&&c.id)}
function partyState(){try{const a=JSON.parse(localStorage.getItem(PARTY)||'null');if(a&&Array.isArray(a.party1)&&Array.isArray(a.party2))return a}catch{}return{party1:[],party2:[]}}
function save(a){localStorage.setItem(PARTY,JSON.stringify(a))}
function profile(c){return c.profile||c.data||{}}
function field(p,...keys){for(const k of keys)if(p&&p[k]!=null)return p[k];return ''}
function info(c){const p=profile(c),name=clean(field(p,'name','characterName'))||clean(c.name)||'Unknown',cls=clean(field(p,'class','className','characterClass'))||'Unknown',role=field(p,'role')||(SUPPORTS.has(cls)?'Support':'DPS');return{name,cls,role:role==='Support'||SUPPORTS.has(cls)?'Support':'DPS',cp:num(field(p,'cp','combatPower')),ilvl:num(field(p,'ilvl','itemLevel')),url:c.url||field(p,'url','profileUrl')||''}}
function text(c){const p=profile(c),b=p.optimizerBuild||p.build||{};return clean([p.rawText,p.text,p.characterText,p.arkGridText,p.arkPassiveText,p.engravingsText,p.gemsText,b.text,b.arkGridText,b.arkPassiveText,b.engravingText,b.gemsText].filter(Boolean).join(' ')).toLowerCase()}
function flags(c){const t=text(c);return{summoner:/summoner|서머너/.test(t),masterSummoner:/master summoner|상급 소환사/.test(t),communicationOverflow:/communication overflow|교감/.test(t),keenBlunt:/keen blunt weapon|keen blunt/.test(t),adrenaline:/adrenaline/.test(t),ambush:/ambush master|back attack|entropy/.test(t),front:/master brawler|front attack/.test(t),raidCaptain:/raid captain/.test(t),swiftness:/swiftness/.test(t),mana:/mana|mp recovery|boundless/.test(t),burst:/burst|igniter|full moon|punisher/.test(t)}}
const SYN={damage:{classes:['Berserker','Shadowhunter','Scrapper','Sorceress','Sharpshooter','Summoner','Destroyer','Artillerist','Reaper','Slayer','Soul Eater','Breaker'],value:.06},crit:{classes:['Arcanist','Arcana','Deadeye','Gunslinger','Wardancer','Striker','Aeromancer'],value:.10},critDamage:{classes:['Glaivier','Glavier'],value:.08},attackSpeed:{classes:['Wardancer','Striker'],value:.08},attackPower:{classes:['Soulfist','Machinist','Scouter'],value:.06},positional:{classes:['Deathblade','Gunlancer'],value:.04},mana:{classes:['Summoner'],value:.08}};
function classMatch(cls,list){const x=cls.toLowerCase().replace(/\s+/g,'');return list.some(v=>x===v.toLowerCase().replace(/\s+/g,''))}
function provided(c){const i=info(c),out=[];for(const[k,v]of Object.entries(SYN))if(classMatch(i.cls,v.classes))out.push({type:k,value:v.value});return out}
function recipientWeight(c,type){const i=info(c),f=flags(c);if(i.role==='Support')return 0;let w=1;if(type==='crit'){if(f.keenBlunt||f.adrenaline||f.burst)w+=.35;if(/crit rate|100.?% crit|full crit/.test(text(c)))w-=.20}if(type==='critDamage'&&(f.keenBlunt||f.burst))w+=.30;if(type==='attackSpeed'&&(f.raidCaptain||f.swiftness))w+=.35;if(type==='positional'){if(f.ambush||f.front)w+=.55;else w*=.65}if(type==='attackPower'&&(f.burst||f.adrenaline))w+=.12;if(type==='mana')w=f.summoner||f.mana?1.55:.35;if(type==='damage'&&f.summoner)w+=.10;return Math.max(0,w)}
function supportEffects(c){const cls=info(c).cls.toLowerCase();if(cls==='artist')return[{type:'supportAmplification',value:.10},{type:'mana',value:.08},{type:'attackSpeed',value:.04}];if(cls==='bard')return[{type:'supportAmplification',value:.10},{type:'attackPower',value:.06},{type:'attackSpeed',value:.035},{type:'mana',value:.12}];if(cls==='paladin')return[{type:'supportAmplification',value:.10},{type:'damage',value:.03}];if(cls==='valkyrie')return[{type:'supportAmplification',value:.095},{type:'attackSpeed',value:.06}];return[{type:'supportAmplification',value:.09}]}
function buildFactor(c){const p=profile(c),f=flags(c);let x=1;if([p.arkGrid,p.arkPassive,p.engravings,p.gems,p.optimizerBuild,p.build].some(Boolean))x+=.01;if(f.masterSummoner)x+=.005;if(f.communicationOverflow)x+=.005;return x}
function contribution(p,target){const i=info(target);if(i.role!=='DPS')return{base:0,build:0,synergy:0,support:0,total:0,details:[]};const cp=i.cp,fac=buildFactor(target);let synergy=0,support=0,details=[];for(const src of p.filter(c=>c!==target&&info(c).role==='DPS'))for(const s of provided(src)){const value=cp*fac*s.value*recipientWeight(target,s.type);synergy+=value;details.push({source:info(src).name,type:s.type,value})}const sup=p.find(c=>info(c).role==='Support');if(sup)for(const e of supportEffects(sup)){const value=cp*fac*e.value*recipientWeight(target,e.type);support+=value;details.push({source:info(sup).name,type:e.type,value})}const build=cp*(fac-1),total=cp+build+synergy+support;return{base:cp,build,synergy,support,total,details}}
function breakdown(p){const dps=p.filter(c=>info(c).role==='DPS'),sup=p.filter(c=>info(c).role==='Support');if(p.length!==4||sup.length!==1)return{total:0,base:0,build:0,synergy:0,support:0,contributions:[]};const contributions=dps.map(c=>({c,...contribution(p,c)}));return{total:contributions.reduce((n,x)=>n+x.total,0),base:contributions.reduce((n,x)=>n+x.base,0),build:contributions.reduce((n,x)=>n+x.build,0),synergy:contributions.reduce((n,x)=>n+x.synergy,0),support:contributions.reduce((n,x)=>n+x.support,0),contributions}}
function partyScore(p){return breakdown(p).total}
function resolve(a){const m=new Map(roster().map(c=>[c.id,c])),p1=[],p2=[],used=new Set();for(const id of a.party1||[])if(m.has(id)&&p1.length<4&&!used.has(id)){p1.push(m.get(id));used.add(id)}for(const id of a.party2||[])if(m.has(id)&&p2.length<4&&!used.has(id)){p2.push(m.get(id));used.add(id)}for(const c of m.values())if(!used.has(c.id)){if(p1.length<4){p1.push(c);used.add(c.id)}else if(p2.length<4){p2.push(c);used.add(c.id)}}return{p1,p2}}
function synergyLabels(p){const out=[];for(const c of p)for(const s of provided(c))if(!out.includes(s.type))out.push(s.type);const sup=p.find(c=>info(c).role==='Support');if(sup&&!out.includes('support amplification'))out.push('support amplification');if(p.some(c=>info(c).role==='DPS'&&flags(c).summoner)&&!out.includes('mana'))out.push('mana');return out.map(x=>x==='supportAmplification'?'support amplification':x)}
const DEFINITIONS={'Base DPS Power':'The starting power of the party’s DPS characters before party bonuses are added.','Build Effect':'How the character’s actual detected build changes their estimated power and how strongly they benefit from different party synergies. This is tied to the detected build, including class choice, Ark Grid core configuration, Ark Passive, engravings, gems, and other relevant build data.','Party Synergy':'The extra power a character gets from useful effects provided by the other DPS characters in their party.','Support Impact':'The extra power a character gets from their support’s buffs and other support effects.'};
function tip(label,value){return `<span class="optimizer-definition-trigger"><span class="optimizer-definition-label">${label}</span><span class="optimizer-definition">${value}</span></span>`}
function member(c,x){const i=info(c),color=i.role==='Support'?'#79c98b':'#e07a7a',base=x?.base||1,details=x?.details?.map(d=>`<div class="chb-synergy"><strong>${esc(d.type)}</strong> from ${esc(d.source)}: ${fmt(d.value)}</div>`).join('')||'';return `<div class="party-member authoritative-member" draggable="true" data-character-id="${esc(c.id)}"><a class="party-character-link" href="${esc(i.url)}" target="_blank" rel="noopener noreferrer">${esc(i.name)}</a><span class="party-class-label">${esc(i.cls)}</span><span class="party-role-label" style="color:${color} !important">${i.role}</span><span class="party-stat-label">iLvl ${fmt(i.ilvl)} · CP ${fmt(i.cp)}</span>${x?`<div class="character-hover-breakdown"><div class="chb-head"><strong>${esc(i.name)}</strong><span>CP ${fmt(x.base)} · Contribution ${fmt(x.total)}</span></div><div class="chb-stats"><span>Build +${(x.build/base*100).toFixed(2)}%</span><span>Synergy +${(x.synergy/base*100).toFixed(2)}%</span><span>Support +${(x.support/base*100).toFixed(2)}%</span></div>${details?`<div class="chb-detail">${details}</div>`:''}</div>`:''}</div>`}
function breakdownHtml(p){const b=breakdown(p),base=b.base||1;return `<div class="party-breakdown"><div class="party-metric">${tip('Base DPS Power',DEFINITIONS['Base DPS Power'])}<strong>${fmt(b.base)}</strong></div><div class="party-metric">${tip('Build Effect',DEFINITIONS['Build Effect'])}<strong>+${(b.build/base*100).toFixed(2)}%</strong></div><div class="party-metric">${tip('Party Synergy',DEFINITIONS['Party Synergy'])}<strong>+${(b.synergy/base*100).toFixed(2)}%</strong></div><div class="party-metric">${tip('Support Impact',DEFINITIONS['Support Impact'])}<strong>+${(b.support/base*100).toFixed(2)}%</strong></div></div>`}
function styles(){if(document.getElementById('optimizer-hover-definitions'))return;const s=document.createElement('style');s.id='optimizer-hover-definitions';s.textContent=`.combined-breakdown{display:flex!important;flex-wrap:wrap!important;gap:12px 30px!important;margin-top:12px!important;line-height:1.5!important}.combined-breakdown>span{white-space:nowrap!important}.party-breakdown{display:flex!important;flex-wrap:wrap!important;gap:10px 28px!important;margin-top:14px!important;line-height:1.5!important}.party-metric{display:inline-flex!important;align-items:center!important;gap:7px!important;position:relative}.optimizer-definition-trigger{position:relative;display:inline-block}.optimizer-definition-label{border-bottom:1px dotted currentColor;cursor:help}.optimizer-definition{display:none;position:absolute;z-index:3000;left:0;bottom:calc(100% + 9px);width:300px;padding:11px 13px;border-radius:7px;background:#17191d;color:#eee;border:1px solid rgba(255,255,255,.18);box-shadow:0 8px 24px rgba(0,0,0,.4);font-size:12px;font-weight:400;line-height:1.55;text-align:left;white-space:normal}.optimizer-definition-trigger:hover>.optimizer-definition{display:block}.authoritative-member{position:relative}.character-hover-breakdown{position:absolute;z-index:3000;left:50%;bottom:calc(100% + 10px);transform:translateX(-50%);display:none;width:330px;padding:12px 14px;border-radius:8px;background:#17191d;color:#eee;border:1px solid rgba(255,255,255,.18);box-shadow:0 8px 24px rgba(0,0,0,.4);font-size:12px;line-height:1.5;text-align:left;pointer-events:none}.authoritative-member:hover>.character-hover-breakdown{display:block}.authoritative-member:hover{z-index:3001}.chb-head,.chb-stats{display:flex;justify-content:space-between;gap:10px}.chb-stats{justify-content:flex-start;margin-top:6px}.chb-detail{display:flex;flex-direction:column;gap:5px;margin-top:9px;color:#bbb}.chb-synergy{display:block;padding:2px 0;line-height:1.45}`;document.head.appendChild(s)}
function render(a,extra=''){styles();const h=document.querySelector('#suggestedParties');if(!h)return;const{p1,p2}=resolve(a),b1=breakdown(p1),b2=breakdown(p2),base=b1.base+b2.base,total=b1.total+b2.total,box=(n,k,p,b)=>`<article class="party authoritative-party" data-party="${k}"><div class="party-heading"><div><h3>${n}</h3><div class="party-score">Estimated potential: <strong>${fmt(b.total)}</strong></div></div><div class="party-meta">${p.length}/4 · ${p.filter(c=>info(c).role==='Support').length} support</div></div><div class="party-dropzone authoritative-dropzone" data-drop-party="${k}">${p.map(c=>member(c,b.contributions.find(x=>x.c===c))).join('')}</div><div class="party-synergies"><strong>Synergies:</strong> ${synergyLabels(p).join(', ')||'None'}</div>${breakdownHtml(p)}</article>`;h.innerHTML=`<div class="authoritative-summary"><strong>Combined estimated potential: ${fmt(total)}</strong><span> — Build-aware individual power with character-specific party synergy interactions.</span><div class="combined-breakdown"><span>${tip('Base DPS Power',DEFINITIONS['Base DPS Power'])} <strong>${fmt(base)}</strong></span><span>${tip('Build Effect',DEFINITIONS['Build Effect'])} <strong>+${base?((b1.build+b2.build)/base*100).toFixed(2):'0.00'}%</strong></span><span>${tip('Party Synergy',DEFINITIONS['Party Synergy'])} <strong>+${base?((b1.synergy+b2.synergy)/base*100).toFixed(2):'0.00'}%</strong></span><span>${tip('Support Impact',DEFINITIONS['Support Impact'])} <strong>+${base?((b1.support+b2.support)/base*100).toFixed(2):'0.00'}%</strong></span></div></div>${box('Party 1','party1',p1,b1)}${box('Party 2','party2',p2,b2)}${extra}`}
function combos(a,k){const out=[];function rec(i,p){if(p.length===k){out.push(p.slice());return}for(let j=i;j<=a.length-(k-p.length);j++)rec(j+1,p.concat(a[j]))}rec(0,[]);return out}
const yieldFrame=()=>new Promise(r=>setTimeout(r,0));
async function optimize(){const list=roster(),b=document.querySelector('#optimizeBtn');if(list.length<8)return;if(b){b.disabled=true;b.textContent='Optimizing…';b.setAttribute('aria-busy','true')}await yieldFrame();try{let best=null,high=-Infinity;const eights=combos(list,8);for(let ei=0;ei<eights.length;ei++){const eight=eights[ei];for(const p1 of combos(eight,4)){const p2=eight.filter(c=>!p1.includes(c));if(p1.filter(c=>info(c).role==='Support').length!==1||p2.filter(c=>info(c).role==='Support').length!==1)continue;const s=partyScore(p1)+partyScore(p2);if(s>high){high=s;best={party1:p1.map(c=>c.id),party2:p2.map(c=>c.id)}}}if((ei&7)===0)await yieldFrame()}if(!best)throw Error('No valid arrangement with exactly one support per party.');save(best);render(best,`<div class="optimizer-result"><strong>Optimization complete.</strong> Best build-aware 8-character arrangement: <strong>${fmt(high)}</strong>.</div>`)}catch(e){console.error(e);render(partyState(),'<div class="optimizer-result">Optimization failed. Current parties preserved.</div>')}finally{if(b){b.disabled=false;b.textContent='Optimize Parties';b.removeAttribute('aria-busy')}}}
function wire(h){h.addEventListener('dragstart',e=>{const m=e.target.closest('.party-member');if(m)e.dataTransfer.setData('text/plain',m.dataset.characterId)});h.addEventListener('dragover',e=>{if(e.target.closest('.party-dropzone'))e.preventDefault()});h.addEventListener('drop',e=>{const z=e.target.closest('.party-dropzone');if(!z)return;e.preventDefault();const id=e.dataTransfer.getData('text/plain'),a=partyState(),from=a.party1.includes(id)?'party1':a.party2.includes(id)?'party2':null,to=z.dataset.dropParty;if(!from)return;const target=e.target.closest('.party-member');if(target&&target.dataset.characterId!==id){const other=target.dataset.characterId,of=a.party1.includes(other)?'party1':a.party2.includes(other)?'party2':null;if(!of||of===from)return;const old=resolve(a),before=partyScore(old.p1)+partyScore(old.p2),i=a[from].indexOf(id),j=a[of].indexOf(other);a[from][i]=other;a[of][j]=id;save(a);const now=resolve(a),after=partyScore(now.p1)+partyScore(now.p2),delta=before?((after-before)/before)*100:0;render(a,`<div class="swap-impact ${delta>=0?'positive':'negative'}"><span class="swap-impact-number">${pct(delta)} combined estimated potential damage.</span></div>`);return}if(to!==from&&a[to].length<4){const old=resolve(a),before=partyScore(old.p1)+partyScore(old.p2);a[from]=a[from].filter(x=>x!==id);a[to].push(id);save(a);const now=resolve(a),after=partyScore(now.p1)+partyScore(now.p2),delta=before?((after-before)/before)*100:0;render(a,`<div class="swap-impact ${delta>=0?'positive':'negative'}"><span class="swap-impact-number">${pct(delta)} combined estimated potential damage.</span></div>`);return}})}
function start(){const h=document.querySelector('#suggestedParties'),b=document.querySelector('#optimizeBtn');if(!h||!b||h.dataset.authoritativeOptimizer)return;h.dataset.authoritativeOptimizer='1';b.addEventListener('click',optimize);wire(h);render(partyState())}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();