(()=>{
'use strict';
const CSS_ID='optimizer-ui-v12-style';
const labels=['Base DPS Power','Build Effect','Party Synergy','Support Impact'];
function addStyle(){if(document.getElementById(CSS_ID))return;const s=document.createElement('style');s.id=CSS_ID;s.textContent=`.optimizer-ui-metric{display:inline-flex!important;align-items:center!important;gap:6px!important;margin-right:24px!important;margin-bottom:8px!important;line-height:1.5!important}.optimizer-ui-metric .metric-value{white-space:nowrap!important}.metric-change{font-size:11px!important;font-weight:700!important;white-space:nowrap!important;margin-left:3px!important}.metric-change.up{color:#55c878!important}.metric-change.down{color:#e66a6a!important}.optimizer-ui-combined{display:flex!important;flex-wrap:wrap!important;gap:8px 2px!important;margin-top:12px!important}.optimizer-ui-party{display:flex!important;flex-wrap:wrap!important;gap:8px 2px!important;margin-top:14px!important}.optimizer-ui-summary{margin-top:10px!important}`;document.head.appendChild(s)}
function parseValue(el){const s=(el?.textContent||'').replace(/,/g,'');const strong=el?.querySelector('strong');const raw=(strong?.textContent||s);const m=raw.match(/[+-]?\d+(?:\.\d+)?/);return m?Number(m[0]):0}
function metrics(){const out={combined:[],parties:[]};document.querySelectorAll('#suggestedParties .combined-breakdown>span').forEach((el,i)=>out.combined[i]=parseValue(el));document.querySelectorAll('#suggestedParties .party-breakdown').forEach((box,pi)=>{out.parties[pi]=[];box.querySelectorAll('.party-metric').forEach((el,i)=>out.parties[pi][i]=parseValue(el))});return out}
function cleanMetric(el,index,change){if(!el)return;el.classList.add('optimizer-ui-metric');let value=el.querySelector('.metric-value');if(!value){const strong=el.querySelector('strong');if(!strong)return;value=document.createElement('span');value.className='metric-value';value.appendChild(strong.cloneNode(true));strong.replaceWith(value)}if(change===null||change===undefined)return;const old=el.querySelector('.metric-change');if(old)old.remove();if(Math.abs(change)<0.005)return;const span=document.createElement('span');span.className='metric-change '+(change>0?'up':'down');const arrow=change>0?'▲':'▼';const suffix=index===0?Math.round(Math.abs(change)).toLocaleString():Math.abs(change).toFixed(2)+'%';span.textContent=`${arrow} ${change>0?'+':'-'}${suffix}`;el.appendChild(span)}
function decorate(){addStyle();const root=document.querySelector('#suggestedParties');if(!root)return;const summary=root.querySelector('.authoritative-summary');if(summary){summary.classList.add('optimizer-ui-summary');const box=summary.querySelector('.combined-breakdown');if(box){box.classList.add('optimizer-ui-combined');box.querySelectorAll(':scope>span').forEach((el,i)=>cleanMetric(el,i,null))}}root.querySelectorAll('.party-breakdown').forEach(box=>{box.classList.add('optimizer-ui-party');box.querySelectorAll('.party-metric').forEach((el,i)=>cleanMetric(el,i,null))})}
function applyChanges(before,after){if(!before||!after)return;after.combined.forEach((v,i)=>{const el=document.querySelector(`#suggestedParties .combined-breakdown>span:nth-child(${i+1})`);cleanMetric(el,i,v-(before.combined[i]??v))});after.parties.forEach((party,i)=>party.forEach((v,j)=>{const el=document.querySelectorAll('#suggestedParties .party-breakdown')[i]?.querySelectorAll('.party-metric')[j];cleanMetric(el,j,v-(before.parties?.[i]?.[j]??v))}))}
let before=null,dragId=null;
document.addEventListener('dragstart',e=>{const m=e.target.closest?.('#suggestedParties .party-member');if(!m)return;dragId=m.dataset.characterId;decorate();before=metrics()},true);
document.addEventListener('drop',e=>{if(!dragId||!before)return;const snapshot=before;const id=dragId;setTimeout(()=>{decorate();const after=metrics();applyChanges(snapshot,after);before=null;dragId=null},150)},true);
const observer=new MutationObserver(()=>decorate());observer.observe(document.body,{childList:true,subtree:true});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',decorate,{once:true});else decorate();
})();
