/* Lost Ark Hideout — optimizer v16: practical party value */
(()=>{
'use strict';
const STORE='lostark-hideout-private-v3',PARTY='lostark-hideout-party-assignments-v2';
const SUPPORTS=new Set(['Bard','Artist','Paladin','Valkyrie']);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number.isFinite(Number(v))?Number(v):0,fmt=v=>Math.round(num(v)).toLocaleString(),pct=v=>`${v>=0?'+':''}${v.toFixed(2)}%`,clean=s=>String(s??'').replace(/\s+/g,' ').trim();
function load(){try{return JSON.parse(localStorage.getItem(STORE)||'null')||{characters:[]}}catch{return{characters:[]}}}
function roster(){return(load().characters||[]).filter(c=>c&&c.id)}
function partyState(){try{const a=JSON.parse(localStorage.getItem(PARTY)||'null');if(a&&Array.isArray(a.party1)&&Array.isArray(a.party2))return a}catch{}return{party1:[],party2:[]}}
function save(a){localStorage.setItem(PARTY,JSON.stringify(a))}
function profile(c){return c.profile||c.data||{}}
function field(p,...keys){for(const k of keys)if(p&&p[k]!=null)return p[k];return ''}
function build(c){try{return window.LostArkBuildProfilesV2?.get(c.url)||{}}catch{return{}}}
function info(c){const p=profile(c),b=build(c),name=clean(field(p,'name','characterName'))||clean(c.name)||'Unknown',cls=clean(field(p,'class','className','characterClass'))||'Unknown',role=field(p,'role')||(SUPPORTS.has(cls)?'Support':'DPS');return{name,cls,role:role==='Support'||SUPPORTS.has(cls)?'Support':'DPS',cp:num(field(p,'cp','combatPower')),ilvl:num(field(p,'ilvl','itemLevel')),url:c.url||field(p,'url','profileUrl')||'',build:b}}
function text(c){const p=profile(c),b=build(c);return clean([p.rawText,p.text,p.characterText,p.arkGridText,p.arkPassiveText,p.engravingsText,p.gemsText,b.text,b.engravings?.join(' '),b.grid?.map(x=>x.name).join(' '),b.arkPassive?.map(x=>x.name).join(' ')].filter(Boolean).join(' ')).toLowerCase()}
function positional(c){const b=build(c),t=text(c);if(b.positional&&b.positional!=='Unknown')return b.positional;if(/ambush master|back attack/.test(t))return'Back Attack';if(/master brawler|front attack/.test(t))return'Front Attack';if(/hit master/.test(t))return'Hit Master';return'Unknown'}
function flags(c){const t=text(c),b=build(c);return{summoner:/summoner|서머너/.test(t)||info(c).cls==='Summoner',masterSummoner:/master summoner|상급 소환사/.test(t),communicationOverflow:/communication overflow|교감/.test(t),keenBlunt:/keen blunt weapon|keen blunt/.test(t),adrenaline:/adrenaline/.test(t),ambush:/ambush master|back attack|entropy/.test(t),front:/master brawler|front attack/.test(t),hitmaster:/hit master/.test(t),raidCaptain:/raid captain/.test(t),swiftness:/swiftness/.test(t),mana:/mana|mp recovery|boundless/.test(t),burst:!!b.burst||/igniter|full moon|punisher|burst/.test(t)}}
const SYN={damage:{classes:['Berserker','Shadowhunter','Scrapper','Sorceress','Sharpshooter','Summoner','Destroyer','Artillerist','Reaper','Slayer','Souleater','Soul Eater','Breaker','Gunlancer'],value:.06},crit:{classes:['Arcanist','Arcana','Deadeye','Gunslinger','Wardancer','Striker','Aeromancer','Glaivier','Glavier'],value:.10},critDamage:{classes:['Glaivier','Glavier'],value:.08},attackSpeed:{classes:['Wardancer','Striker','Deathblade','Gunlancer'],value:.08},attackPower:{classes:['Soulfist','Machinist','Scouter'],value:.06},positional:{classes:['Deathblade','Gunlancer'],value:.04},mana:{classes:['Summoner'],value:.08}};
function classMatch(cls,list){const x=String(cls).toLowerCase().replace(/\s+/g,'');return list.some(v=>x===v.toLowerCase().replace(/\s+/g,''))}
function provided(c){const i=info(c),out=[];for(const[k,v]of Object.entries(SYN))if(classMatch(i.cls,v.classes))out.push({type:k,value:v.value});return out}
function recipientWeight(c,type){const f=flags(c),i=info(c);if(i.role!=='DPS')return 0;let w=1;if(type==='crit'){if(f.keenBlunt||f.adrenaline||f.burst)w+=.35;if(/100.?% crit|full crit/.test(text(c)))w-=.30}if(type==='critDamage'&&(f.keenBlunt||f.burst))w+=.30;if(type==='attackSpeed'&&(f.raidCaptain||f.swiftness))w+=.35;if(type==='positional'){const pos=positional(c);w=pos==='Back Attack'||pos==='Front Attack'?1.35:pos==='Hit Master'?.55:.85}if(type==='attackPower'&&(f.burst||f.adrenaline))w+=.12;if(type==='mana')w=f.summoner||f.mana?1.55:.20;if(type==='damage'&&f.summoner)w+=.10;return Math.max(0,w)}
function supportEffects(c){const cls=info(c).cls.toLowerCase();if(cls==='artist')return[{type:'supportAmplification',value:.10},{type:'mana',value:.08},{type:'attackSpeed',value:.04}];if(cls==='bard')return[{type:'supportAmplification',value:.10},{type:'attackPower',value:.06},{type:'attackSpeed',value:.035},{type:'mana',value:.12}];if(cls==='paladin')return[{type:'supportAmplification',value:.10},{type:'damage',value:.03}];if(cls==='valkyrie')return[{type:'supportAmplification',value:.095},{type:'attackSpeed',value:.06}];return[{type:'supportAmplification',value:.09}]}
function supportUptime(p,target){const sup=p.find(c=>info(c).role==='Support');if(!sup)return 0;const sc=info(sup).cls, positions=p.filter(c=>info(c).role==='DPS').map(positional);const known=[...new Set(positions.filter(x=>x!=='Unknown'))];const hasFront=known.includes('Front Attack'),hasBack=known.includes('Back Attack'),hasHM=known.includes('Hit Master');let u;if(sc==='Paladin'||sc==='Valkyrie'){u=known.length>=3?.94:hasFront&&hasBack?.96:.99}else{u=known.length>=3?.72:hasFront&&hasBack?.76:hasHM&&(hasFront||hasBack)?.84:.95}const tp=positional(target);if((sc==='Bard'||sc==='Artist')&&tp==='Hit Master'&&known.length>=2)u-=.05;if((sc==='Bard'||sc==='Artist')&&tp!=='Unknown'&&known.length===1)u+=.02;return Math.max(.60,Math.min(1,u))}
function buildFit(c){const b=build(c),f=flags(c);let x=0;if(b.engravings?.length)x+=.004;if(b.grid?.length)x+=.004;if(b.arkPassive?.length)x+=.004;if(f.masterSummoner||f.communicationOverflow)x+=.002;return x}
function contribution(p,target){const i=info(target);if(i.role!=='DPS')return{base:0,build:0,synergy:0,support:0,total:0,details:[]};const cp=i.cp,fit=buildFit(target),base=cp,buildValue=cp*fit;let synergy=0,support=0,details=[];for(const src of p.filter(c=>c!==target&&info(c).role==='DPS'))for(const s of provided(src)){const value=cp*s.value*recipientWeight(target,s.type);synergy+=value;details.push({source:info(src).name,type:s.type,value})}const sup=p.find(c=>info(c).role==='Support');if(sup){const uptime=supportUptime(p,target);for(const e of supportEffects(sup)){const value=cp*e.value*recipientWeight(target,e.type)*uptime;support+=value;details.push({source:info(sup).name,type:e.type,value,uptime})}}return{base,build:buildValue,synergy,support,total:base+buildValue+synergy+support,details,uptime:sup?supportUptime(p,target):0}}
function breakdown(p){const dps=p.filter(c=>info(c).role==='DPS'),sup=p.filter(c=>info(c).role==='Support');if(p.length!==4||sup.length!==1)return{total:0,base:0,build:0,synergy:0,support:0,contributions:[],coherence:0};const contributions=dps.map(c=>({c,...contribution(p,c)}));return{total:contributions.reduce((n,x)=>n+x.total,0),base:contributions.reduce((n,x)=>n+x.base,0),build:contributions.reduce((n,x)=>n+x.build,0),synergy:contributions.reduce((n,x)=>n+x.synergy,0),support:contributions.reduce((n,x)=>n+x.support,0),contributions,coherence:Math.round((contributions.reduce((n,x)=>n+x.uptime,0)/dps.length)*100)} }
function partyScore(p){return breakdown(p).total}
function resolve(a){const m=new Map(roster().map(c=>[c.id,c])),p1=[],p2=[],used=new Set();for(const id of a.party1||[])if(m.has(id)&&p1.length<4&&!used.has(id)){p1.push(m.get(id));used.add(id)}for(const id of a.party2||[])if(m.has(id)&&p2.length<4&&!used.has(id)){p2.push(m.get(id));used.add(id)}for(const c of m.values())if(!used.has(c.id)){if(p1.length<4){p1.push(c);used.add(c.id)}else if(p2.length<4){p2.push(c);used.add(c.id)}}return{p1,p2}}
function synergyLabels(p){const out=[];for(const c of p)for(const s of provided(c))if(!out.includes(s.type))out.push(s.type);if(p.some(c=>info(c).role==='Support')&&!out.includes('support amplification'))out.push('support amplification');if(p.some(c=>flags(c).summoner)&&!out.includes('mana'))out.push('mana');return out.map(x=>x==='supportAmplification'?'support amplification':x)}
const DEFINITIONS={'Base DPS Power':'The starting power of the DPS characters before party bonuses.','Build Effect':'A small adjustment based on the build actually detected on the character, including class choice, Ark Grid core configuration, Ark Passive, engravings, gems, and other relevant build data.','Party Synergy':'Extra value from useful effects supplied by the other DPS characters in the same party. The model checks whether the character can actually benefit from the effect instead of treating every synergy as equally valuable.','Support Impact':'Extra value from the support. This is adjusted for expected uptime and how well the party’s positioning fits the support. A mixed front/back/Hit Master party can reduce uptime for supports with more positional buffing.'};
function tip(label,value){return `<span class="optimizer-definition-trigger"><span class="optimizer-definition-label">${label}</span><span class="optimizer-definition">${value}</span></span>`}
function changeMark(delta,type='number'){if(Math.abs(delta)<0.0001)return '';const up=delta>0,arrow=up?'▲':'▼',cls=up?'metric-up':'metric-down';return `<span class="metric-change ${cls}">${arrow} ${type==='pct'?Math.abs(delta).toFixed(2)+' pts':Math.abs(delta)<1?Math.abs(delta).toFixed(2):fmt(Math.abs(delta))}</span>`}
function metric(label,value,definition,diff,type='number'){return `<div class="party-metric">${tip(label,definition)} <strong>${value}</strong>${changeMark(diff,type)}</div>`}
function member(c,x){const i=info(c),color=i.role==='Support'?'#79c98b':'#e07a7a',base=x?.base||1,details=x?.details?.map(d=>`<div class="chb-synergy"><strong>${esc(d.type)}</strong> from ${esc(d.source)}: ${fmt(d.value)}${d.uptime?` · uptime ${(d.uptime*100).toFixed(0)}%`:''}</div>`).join('')||'';return `<div class="party-member authoritative-member" draggable="true" data-character-id="${esc(c.id)}"><a class="party-character-link" href="${esc(i.url)}" target="_blank" rel="noopener noreferrer">${esc(i.name)}</a><span class="party-class-label">${esc(i.cls)}</span><span class="party-role-label" style="color:${color}!important">${i.role}</span><span class="party-stat-label">${esc(positional(c))} · CP ${fmt(i.cp)}</span><div class="character-hover-breakdown"><div class="chb-head"><strong>${esc(i.name)}</strong><span>CP ${fmt(x?.base||i.cp)} · Contribution ${fmt(x?.total||0)}</span></div><div class="chb-stats"><span>Build +${((x?.build||0)/(x?.base||1)*100).toFixed(2)}%</span><span>Synergy +${((x?.synergy||0)/(x?.base||1)*100).toFixed(2)}%</span><span>Support +${((x?.support||0)/(x?.base||1)*100).toFixed(2)}%</span><span>Support uptime ${x?.uptime?Math.round(x.uptime*100):0}%</span></div><div class="chb-detail">${details||'<div>No direct party effects detected.</div>'}</div></div></div>`}
function styles(){if(document.getElementById('optimizer-v16-style'))return;const s=document.createElement('style');s.id='optimizer-v16-style';s.textContent=`.combined-breakdown,.party-breakdown{display:flex!important;flex-wrap:wrap!important;gap:10px 28px!important;margin-top:12px!important;line-height:1.55!important}.combined-breakdown>span,.party-breakdown>.party-metric{white-space:nowrap!important}.party-metric{display:inline-flex!important;align-items:center!important;gap:7px!important;position:relative}.metric-change{font-size:12px;font-weight:700;white-space:nowrap}.metric-up{color:#65c878}.metric-down{color:#ef6b6b}.optimizer-definition-trigger{position:relative;display:inline-block}.optimizer-definition-label{border-bottom:1px dotted currentColor;cursor:help}.optimizer-definition{display:none;position:absolute;z-index:3000;left:0;bottom:calc(100% + 9px);width:310px;padding:11px 13px;border-radius:7px;background:#17191d;color:#eee;border:1px solid rgba(255,255,255,.18);box-shadow:0 8px 24px rgba(0,0,0,.4);font-size:12px;font-weight:400;line-height:1.55;text-align:left;white-space:normal}.optimizer-definition-trigger:hover>.optimizer-definition{display:block}.authoritative-member{position:relative}.character-hover-breakdown{position:absolute;z-index:3000;left:50%;bottom:calc(100% + 10px);transform:translateX(-50%);display:none;width:350px;padding:12px 14px;border-radius:8px;background:#17191d;color:#eee;border:1px solid rgba(255,255,255,.18);box-shadow:0 8px 24px rgba(0,0,0,.4);font-size:12px;line-height:1.5;text-align:left;pointer-events:none}.authoritative-member:hover>.character-hover-breakdown{display:block}.authoritative-member:hover{z-index:3001}.chb-head,.chb-stats{display:flex;justify-content:space-between;gap:10px}.chb-stats{justify-content:flex-start;flex-wrap:wrap;margin-top:6px}.chb-detail{display:flex;flex-direction:column;gap:5px;margin-top:9px;color:#bbb}.chb-synergy{display:block;padding:2px 0;line-height:1.45}`;document.head.appendChild(s)}
function diffBreakdown(before,after){const bp=before.base||0,ap=after.base||0,ratio=k=>v=>v?(v/(v===before[k]?bp:ap)*100):0;return{base:ap-bp,buildPct:(ap?after.build/ap*100:0)-(bp?before.build/bp*100:0),synergyPct:(ap?after.synergy/ap*100:0)-(bp?before.synergy/bp*100:0),supportPct:(ap?after.support/ap*100:0)-(bp?before.support/bp*100:0),total:after.total-before.total,totalPct:before.total?((after.total-before.total)/before.total)*100:0}}
function render(a,extra='',diffs={}){styles();const h=document.querySelector('#suggestedParties');if(!h)return;const{p1,p2}=resolve(a),b1=breakdown(p1),b2=breakdown(p2),base=b1.base+b2.base,total=b1.total+b2.total,cd=diffs.combined||{};const box=(n,k,p,b)=>`<article class="party authoritative-party" data-party="${k}"><div class="party-heading"><div><h3>${n}</h3><div class="party-score">Estimated potential: <strong>${fmt(b.total)}</strong>${changeMark(diffs[k]?.total||0)} ${diffs[k]?.totalPct?`(${pct(diffs[k].totalPct)})`:''}</div></div><div class="party-meta">${p.length}/4 · ${p.filter(c=>info(c).role==='Support').length} support</div></div><div class="party-dropzone authoritative-dropzone" data-drop-party="${k}">${p.map(c=>member(c,b.contributions.find(x=>x.c===c))).join('')}</div><div class="party-synergies"><strong>Synergies:</strong> ${synergyLabels(p).join(', ')||'None'} · Support uptime ${b.coherence}%</div><div class="party-breakdown">${metric('Base DPS Power',fmt(b.base),DEFINITIONS['Base DPS Power'],diffs[k]?.base||0)}${metric('Build Effect','+'+(b.base?b.build/b.base*100:0).toFixed(2)+'%',DEFINITIONS['Build Effect'],diffs[k]?.buildPct||0,'pct')}${metric('Party Synergy','+'+(b.base?b.synergy/b.base*100:0).toFixed(2)+'%',DEFINITIONS['Party Synergy'],diffs[k]?.synergyPct||0,'pct')}${metric('Support Impact','+'+(b.base?b.support/b.base*100:0).toFixed(2)+'%',DEFINITIONS['Support Impact'],diffs[k]?.supportPct||0,'pct')}</div></article>`;h.innerHTML=`<div class="authoritative-summary"><strong>Combined estimated potential: ${fmt(total)}</strong>${cd.total?` ${changeMark(cd.total)} (${pct(cd.totalPct)})`:''}<span> — Practical party value using detected builds, party synergies, and support-position compatibility.</span><div class="combined-breakdown"><span>${tip('Base DPS Power',DEFINITIONS['Base DPS Power'])} <strong>${fmt(base)}</strong>${changeMark(cd.base||0)}</span><span>${tip('Build Effect',DEFINITIONS['Build Effect'])} <strong>+${base?((b1.build+b2.build)/base*100).toFixed(2):'0.00'}%</strong>${changeMark(cd.buildPct||0,'pct')}</span><span>${tip('Party Synergy',DEFINITIONS['Party Synergy'])} <strong>+${base?((b1.synergy+b2.synergy)/base*100).toFixed(2):'0.00'}%</strong>${changeMark(cd.synergyPct||0,'pct')}</span><span>${tip('Support Impact',DEFINITIONS['Support Impact'])} <strong>+${base?((b1.support+b2.support)/base*100).toFixed(2):'0.00'}%</strong>${changeMark(cd.supportPct||0,'pct')}</span></div></div>${box('Party 1','party1',p1,b1)}${box('Party 2','party2',p2,b2)}${extra}`}
function combos(a,k){const out=[];function rec(i,p){if(p.length===k){out.push(p.slice());return}for(let j=i;j<=a.length-(k-p.length);j++)rec(j+1,p.concat(a[j]))}rec(0,[]);return out}
const yieldFrame=()=>new Promise(r=>setTimeout(r,0));
async function optimize(){const list=roster(),b=document.querySelector('#optimizeBtn');if(list.length<8)return;if(b){b.disabled=true;b.textContent='Optimizing…';b.setAttribute('aria-busy','true')}await yieldFrame();try{let best=null,high=-Infinity;const eight=list.slice(0,8);for(const p1 of combos(eight,4)){const p2=eight.filter(c=>!p1.includes(c));if(p1.filter(c=>info(c).role==='Support').length!==1||p2.filter(c=>info(c).role==='Support').length!==1)continue;const s=partyScore(p1)+partyScore(p2);if(s>high){high=s;best={party1:p1.map(c=>c.id),party2:p2.map(c=>c.id)}}await yieldFrame()}if(!best)throw Error('No valid arrangement with exactly one support per party.');save(best);render(best,`<div class="optimizer-result"><strong>Optimization complete.</strong> Best practical 8-character arrangement: <strong>${fmt(high)}</strong>.</div>`)}catch(e){console.error(e);render(partyState(),'<div class="optimizer-result">Optimization failed. Current parties preserved.</div>')}finally{if(b){b.disabled=false;b.textContent='Optimize Parties';b.removeAttribute('aria-busy')}}}
function wire(h){h.addEventListener('dragstart',e=>{const m=e.target.closest('.party-member');if(m)e.dataTransfer.setData('text/plain',m.dataset.characterId)});h.addEventListener('dragover',e=>{if(e.target.closest('.party-dropzone'))e.preventDefault()});h.addEventListener('drop',e=>{const z=e.target.closest('.party-dropzone');if(!z)return;e.preventDefault();const id=e.dataTransfer.getData('text/plain'),a=partyState(),from=a.party1.includes(id)?'party1':a.party2.includes(id)?'party2':null,to=z.dataset.dropParty;if(!from)return;const target=e.target.closest('.party-member');if(target&&target.dataset.characterId!==id){const other=target.dataset.characterId,of=a.party1.includes(other)?'party1':a.party2.includes(other)?'party2':null;if(!of||of===from)return;const old=resolve(a),before1=breakdown(old.p1),before2=breakdown(old.p2),beforeTotal=before1.total+before2.total,i=a[from].indexOf(id),j=a[of].indexOf(other);a[from][i]=other;a[of][j]=id;save(a);const now=resolve(a),after1=breakdown(now.p1),after2=breakdown(now.p2),afterTotal=after1.total+after2.total,diffs={party1:diffBreakdown(before1,after1),party2:diffBreakdown(before2,after2),combined:diffBreakdown({base:before1.base+before2.base,build:before1.build+before2.build,synergy:before1.synergy+before2.synergy,support:before1.support+before2.support,total:beforeTotal},{base:after1.base+after2.base,build:after1.build+after2.build,synergy:after1.synergy+after2.synergy,support:after1.support+after2.support,total:afterTotal})};render(a,'',diffs);return}if(to!==from&&a[to].length<4){const old=resolve(a),before1=breakdown(old.p1),before2=breakdown(old.p2),beforeTotal=before1.total+before2.total;a[from]=a[from].filter(x=>x!==id);a[to].push(id);save(a);const now=resolve(a),after1=breakdown(now.p1),after2=breakdown(now.p2),afterTotal=after1.total+after2.total,diffs={party1:diffBreakdown(before1,after1),party2:diffBreakdown(before2,after2),combined:diffBreakdown({base:before1.base+before2.base,build:before1.build+before2.build,synergy:before1.synergy+before2.synergy,support:before1.support+before2.support,total:beforeTotal},{base:after1.base+after2.base,build:after1.build+after2.build,synergy:after1.synergy+after2.synergy,support:after1.support+after2.support,total:afterTotal})};render(a,'',diffs)}})}
function start(){const h=document.querySelector('#suggestedParties'),b=document.querySelector('#optimizeBtn');if(!h||!b||h.dataset.optimizerV16)return;h.dataset.optimizerV16='1';b.addEventListener('click',optimize);wire(h);render(partyState())}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();