/* Lost Ark Hideout — authoritative optimizer v13.
   Single execution path. Build-aware party optimizer with visible async progress and score breakdowns. */
(()=>{
'use strict';
const STORE='lostark-hideout-private-v3',PARTY='lostark-hideout-party-assignments-v2';
const SUPPORTS=new Set(['Bard','Artist','Paladin','Valkyrie']);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number.isFinite(Number(v))?Number(v):0,fmt=v=>Math.round(num(v)).toLocaleString(),pct=v=>`${v>=0?'+':''}${v.toFixed(2)}%`,clean=s=>String(s??'').replace(/\s+/g,' ').trim();
function load(){try{return JSON.parse(localStorage.getItem(STORE)||'null')||{characters:[]}}catch{return{characters:[]}}}
function roster(){return(load().characters||[]).filter(c=>c&&c.id)}
function partyState(){try{const a=JSON.parse(localStorage.getItem(PARTY)||'null');if(a&&Array.isArray(a.party1)&&Array.isArray(a.party2))return a}catch{}return{party1:[],party2:[]}}
function save(a){localStorage.setItem(PARTY,JSON.stringify(a))}
function profile(c){return c.profile||c.data||{}}
function field(p,...keys){for(const k of keys)if(p&&p[k]!=null)return p[k];return ''}
function info(c){const p=profile(c),name=clean(field(p,'name','characterName'))||clean(c.name)||'Unknown',cls=clean(field(p,'class','className','characterClass'))||'Unknown',role=field(p,'role')||(SUPPORTS.has(cls)?'Support':'DPS');return{name,cls,role:role==='Support'||SUPPORTS.has(cls)?'Support':'DPS',cp:num(field(p,'cp','combatPower')),ilvl:num(field(p,'ilvl','itemLevel')),url:c.url||field(p,'url','profileUrl')||''}}
function text(c){const p=profile(c),b=p.optimizerBuild||p.build||{};return clean([p.rawText,p.text,p.characterText,p.arkGridText,p.arkPassiveText,p.engravingsText,p.gemsText,b.text,b.arkGridText,b.arkPassiveText,b.engravingText,b.gemsText].filter(Boolean).join(' ')).toLowerCase()}
function flags(c){const t=text(c);return{summoner:/summoner|서머너/.test(t),masterSummoner:/master summoner|상급 소환사/.test(t),communicationOverflow:/communication overflow|교감/.test(t),keenBlunt:/keen blunt weapon|keen blunt/.test(t),adrenaline:/adrenaline/.test(t),ambush:/ambush master|back attack|entropy/.test(t),front:/master brawler|front attack/.test(t),raidCaptain:/raid captain/.test(t),swiftness:/swiftness/.test(t),specialization:/specialization/.test(t),mana:/mana|mp recovery|boundless/.test(t),burst:/burst|igniter|full moon|punisher/.test(t)}}
const SYN={damage:{classes:['Berserker','Shadowhunter','Scrapper','Sorceress','Sharpshooter','Summoner','Destroyer','Artillerist','Reaper','Slayer','Soul Eater','Breaker'],value:.06},crit:{classes:['Arcanist','Arcana','Deadeye','Gunslinger','Wardancer','Striker','Aeromancer'],value:.10},critDamage:{classes:['Glaivier','Glavier'],value:.08},attackSpeed:{classes:['Wardancer','Striker'],value:.08},attackPower:{classes:['Soulfist','Machinist','Scouter'],value:.06},positional:{classes:['Deathblade','Gunlancer'],value:.04},mana:{classes:['Summoner'],value:.08}};
function classMatch(cls,list){const x=cls.toLowerCase().replace(/\s+/g,'');return list.some(v=>x===v.toLowerCase().replace(/\s+/g,''))}
function provided(c){const i=info(c),out=[];for(const[k,v]of Object.entries(SYN))if(classMatch(i.cls,v.classes))out.push({type:k,value:v.value});return out}
function recipientWeight(c,type){const i=info(c),f=flags(c);if(i.role==='Support')return 0;let w=1;if(type==='crit'){if(f.keenBlunt||f.adrenaline||f.burst)w+=.35;if(/crit rate|100.?% crit|full crit/.test(text(c)))w-=.20}if(type==='critDamage'&&(f.keenBlunt||f.burst))w+=.30;if(type==='attackSpeed'&&(f.raidCaptain||f.swiftness))w+=.35;if(type==='positional'){if(f.ambush||f.front)w+=.55;else w*=.65}if(type==='attackPower'&&(f.burst||f.adrenaline))w+=.12;if(type==='mana')w=f.summoner||f.mana?1.55:.35;if(type==='damage'&&f.summoner)w+=.10;return Math.max(0,w)}
function supportEffects(c){const cls=info(c).cls.toLowerCase();if(cls==='artist')return[{type:'supportAmplification',value:.10},{type:'mana',value:.08},{type:'attackSpeed',value:.04}];if(cls==='bard')return[{type:'supportAmplification',value:.10},{type:'attackPower',value:.06},{type:'attackSpeed',value:.035},{type:'mana',value:.12}];if(cls==='paladin')return[{type:'supportAmplification',value:.10},{type:'damage',value:.03}];if(cls==='valkyrie')return[{type:'supportAmplification',value:.095},{type:'attackSpeed',value:.06}];return[{type:'supportAmplification',value:.09}]}
function buildFactor(c){const p=profile(c),f=flags(c);let x=1;if([p.arkGrid,p.arkPassive,p.engravings,p.gems,p.optimizerBuild,p.build].some(Boolean))x+=.01;if(f.masterSummoner)x+=.005;if(f.communicationOverflow)x+=.005;return x}
function breakdown(p){if(p.length!==4)return{total:0,base:0,build:0,synergy:0,support:0};const sup=p.filter(c=>info(c).role==='Support'),dps=p.filter(c=>info(c).role==='DPS');if(sup.length!==1)return{total:0,base:0,build:0,synergy:0,support:0};let base=0,build=0,synergy=0,support=0;for(const c of dps){const cp=info(c).cp,fac=buildFactor(c);base+=cp;build+=cp*(fac-1)}for(const src of dps)for(const syn of provided(src))for(const target of dps.filter(t=>t!==src))synergy+=info(target).cp*buildFactor(target)*syn.value*recipientWeight(target,syn.type);for(const e of supportEffects(sup[0]))for(const target of dps)support+=info(target).cp*buildFactor(target)*e.value*recipientWeight(target,e.type);return{total:base+build+synergy+support,base,build,synergy,support}}
function partyScore(p){return breakdown(p).total}
function resolve(a){const m=new Map(roster().map(c=>[c.id,c])),p1=[],p2=[],used=new Set();for(const id of a.party1||[])if(m.has(id)&&p1.length<4&&!used.has(id)){p1.push(m.get(id));used.add(id)}for(const id of a.party2||[])if(m.has(id)&&p2.length<4&&!used.has(id)){p2.push(m.get(id));used.add(id)}for(const c of m.values())if(!used.has(c.id)){if(p1.length<4){p1.push(c);used.add(c.id)}else if(p2.length<4){p2.push(c);used.add(c.id)}}return{p1,p2}}
function synergyLabels(p){const out=[];for(const c of p)for(const s of provided(c))if(!out.includes(s.type))out.push(s.type);const sup=p.find(c=>info(c).role==='Support');if(sup&&!out.includes('support amplification'))out.push('support amplification');if(p.some(c=>info(c).role==='DPS'&&flags(c).summoner)&&!out.includes('mana'))out.push('mana');return out.map(x=>x==='supportAmplification'?'support amplification':x)}
function member(c){const i=info(c),color=i.role==='Support'?'#79c98b':'#e07a7a';return `<div class="party-member authoritative-member" draggable="true" data-character-id="${esc(c.id)}"><a class="party-character-link" href="${esc(i.url)}" target="_blank" rel="noopener noreferrer">${esc(i.name)}</a><span class="party-class-label">${esc(i.cls)}</span><span class="party-role-label" style="color:${color} !important">${i.role}</span><span class="party-stat-label">iLvl ${fmt(i.ilvl)} · CP ${fmt(i.cp)}</span></div>`}
function breakdownHtml(p){const b=breakdown(p),synPct=b.base?b.synergy/b.base*100:0,supPct=b.base?b.support/b.base*100:0,buildPct=b.base?b.build/b.base*100:0;return `<div class="party-breakdown"><div><span>Base DPS CP</span><strong>${fmt(b.base)}</strong></div><div><span>Build adjustment</span><strong>${buildPct>=0?'+':''}${buildPct.toFixed(2)}%</strong></div><div><span>Party synergy</span><strong>${synPct>=0?'+':''}${synPct.toFixed(2)}%</strong></div><div><span>Support contribution</span><strong>${supPct>=0?'+':''}${supPct.toFixed(2)}%</strong></div></div>`}
function render(a,extra=''){const h=document.querySelector('#suggestedParties');if(!h)return;const{p1,p2}=resolve(a),box=(n,k,p)=>`<article class="party authoritative-party" data-party="${k}"><div class="party-heading"><div><h3>${n}</h3><div class="party-score">Estimated potential: <strong>${fmt(partyScore(p))}</strong></div></div><div class="party-meta">${p.length}/4 · ${p.filter(c=>info(c).role==='Support').length} support</div></div><div class="party-dropzone authoritative-dropzone" data-drop-party="${k}">${p.map(member).join('')}</div><div class="party-synergies"><strong>Synergies:</strong> ${synergyLabels(p).join(', ')||'None'}</div>${breakdownHtml(p)}</article>`;const d1=breakdown(p1),d2=breakdown(p2),base=d1.base+d2.base,total=d1.total+d2.total;h.innerHTML=`<div class="authoritative-summary"><strong>Combined estimated potential: ${fmt(total)}</strong><span> — Build-aware individual power with character-specific party synergy interactions.</span><div class="combined-breakdown"><span>Base DPS CP: <strong>${fmt(base)}</strong></span><span>Build adjustment: <strong>+${base?((d1.build+d2.build)/base*100).toFixed(2):'0.00'}%</strong></span><span>Party synergy: <strong>+${base?((d1.synergy+d2.synergy)/base*100).toFixed(2):'0.00'}%</strong></span><span>Support contribution: <strong>+${base?((d1.support+d2.support)/base*100).toFixed(2):'0.00'}%</strong></span></div></div>${box('Party 1','party1',p1)}${box('Party 2','party2',p2)}${extra}`}
function combos(a,k){const out=[];function rec(i,p){if(p.length===k){out.push(p.slice());return}for(let j=i;j<=a.length-(k-p.length);j++)rec(j+1,p.concat(a[j]))}rec(0,[]);return out}
const yieldFrame=()=>new Promise(r=>setTimeout(r,0));
async function optimize(){const list=roster(),b=document.querySelector('#optimizeBtn');if(list.length<8){render(partyState(),'<div class="optimizer-result">Add at least 8 characters to optimize parties.</div>');return}if(b){b.disabled=true;b.textContent='Optimizing…';b.setAttribute('aria-busy','true')}await yieldFrame();try{let best=null,high=-Infinity;const eights=combos(list,8);for(let ei=0;ei<eights.length;ei++){const eight=eights[ei];for(const p1 of combos(eight,4)){const p2=eight.filter(c=>!p1.includes(c));if(p1.filter(c=>info(c).role==='Support').length!==1||p2.filter(c=>info(c).role==='Support').length!==1)continue;const s=partyScore(p1)+partyScore(p2);if(s>high){high=s;best={party1:p1.map(c=>c.id),party2:p2.map(c=>c.id)}}}if((ei&7)===0)await yieldFrame()}if(!best)throw Error('No valid arrangement with exactly one support per party.');save(best);render(best,`<div class="optimizer-result"><strong>Optimization complete.</strong> Best build-aware 8-character arrangement: <strong>${fmt(high)}</strong>.</div>`)}catch(e){console.error(e);render(partyState(),'<div class="optimizer-result">Optimization failed. Current parties preserved.</div>')}finally{if(b){b.disabled=false;b.textContent='Optimize Parties';b.removeAttribute('aria-busy')}}}
function wire(h){h.addEventListener('dragstart',e=>{const m=e.target.closest('.party-member');if(m)e.dataTransfer.setData('text/plain',m.dataset.characterId)});h.addEventListener('dragover',e=>{if(e.target.closest('.party-dropzone'))e.preventDefault()});h.addEventListener('drop',e=>{const z=e.target.closest('.party-dropzone');if(!z)return;e.preventDefault();const id=e.dataTransfer.getData('text/plain'),a=partyState(),from=a.party1.includes(id)?'party1':a.party2.includes(id)?'party2':null,to=z.dataset.dropParty;if(!from)return;const target=e.target.closest('.party-member');if(target&&target.dataset.characterId!==id){const other=target.dataset.characterId,of=a.party1.includes(other)?'party1':a.party2.includes(other)?'party2':null;if(!of||of===from)return;const old=resolve(a),before=partyScore(old.p1)+partyScore(old.p2),i=a[from].indexOf(id),j=a[of].indexOf(other);a[from][i]=other;a[of][j]=id;save(a);const now=resolve(a),after=partyScore(now.p1)+partyScore(now.p2),delta=before?((after-before)/before)*100:0;render(a,`<div class="swap-impact ${delta>=0?'positive':'negative'}"><span class="swap-impact-number">${pct(delta)} combined estimated potential damage.</span></div>`);return}if(to!==from&&a[to].length<4){const old=resolve(a),before=partyScore(old.p1)+partyScore(old.p2);a[from]=a[from].filter(x=>x!==id);a[to].push(id);save(a);const now=resolve(a),after=partyScore(now.p1)+partyScore(now.p2),delta=before?((after-before)/before)*100:0;render(a,`<div class="swap-impact ${delta>=0?'positive':'negative'}"><span class="swap-impact-number">${pct(delta)} combined estimated potential damage.</span></div>`)}})}
function start(){const h=document.querySelector('#suggestedParties'),b=document.querySelector('#optimizeBtn');if(!h||!b||h.dataset.authoritativeOptimizer)return;h.dataset.authoritativeOptimizer='1';b.addEventListener('click',optimize);wire(h);render(partyState())}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();