/* Lost Ark Hideout — build-aware party optimizer v10 engine. */
(()=>{
const STORAGE='lostark-hideout-private-v3', PARTY='lostark-hideout-party-assignments-v2';
const CONNECTOR='https://lostark-bible-connector.seraph0226.workers.dev/character';
const SUPPORTS=new Set(['Bard','Artist','Paladin','Valkyrie']);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Math.round(Number(n)||0).toLocaleString();
const pct=n=>`${n>=0?'+':''}${n.toFixed(2)}%`;
function state(){try{return JSON.parse(localStorage.getItem(STORAGE)||'null')||{characters:[]}}catch{return{characters:[]}}}
function chars(){return(state().characters||[]).filter(c=>c&&c.profile)}
function assignments(){try{const a=JSON.parse(localStorage.getItem(PARTY)||'null');if(a&&Array.isArray(a.party1)&&Array.isArray(a.party2))return a}catch{}return{party1:[],party2:[]}}
function save(a){localStorage.setItem(PARTY,JSON.stringify(a))}
function identity(c){const p=c.profile||{},card=[...document.querySelectorAll('#roster .character')].find(x=>x.querySelector('.remove-character')?.dataset.id===c.id),cls=(card?.querySelector('.class')?.textContent||p.class||'Unknown').trim();return{name:card?.querySelector('.character-bible-link')?.textContent?.trim()||p.name||c.name||'',cls,role:p.role==='Support'||SUPPORTS.has(cls)?'Support':'DPS',il:Number(p.ilvl)||0,cp:Number(p.cp)||0,url:c.url}}
function norm(s){return String(s||'').replace(/\s+/g,' ').trim()}
function metric(text,label){const safe=label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),m=text.match(new RegExp(safe+'[^%]{0,100}([+-]?\\d+(?:\\.\\d+)?)%','i'));return m?Number(m[1]):0}
function buildText(c){const b=c.profile?.optimizerBuild||{};return norm([b.text,b.snippet,b.engravingText,b.arkGridText,b.arkPassiveText].filter(Boolean).join(' '))}
function buildMetrics(c){const t=buildText(c);return{arkPassive:metric(t,'Ark Passive'),arkGrid:metric(t,'Ark Grid'),engravings:metric(t,'Engravings'),accessory:metric(t,'Accessory Effects'),bracelet:metric(t,'Bracelet Effects'),gems:metric(t,'Gems'),raw:t}}
const SYNERGY={damage:['berserker','shadowhunter','scrapper','sorceress','sharpshooter','summoner','destroyer','artillerist','reaper','gunlancer'],attackPower:['soulfist','machinist'],positional:['deathblade','gunlancer'],crit:['arcanist','arcana','deadeye','gunslinger','wardancer','striker','glaivier','glavier'],attackSpeed:['wardancer','striker','gunlancer','deathblade'],critDamage:['glaivier','glavier']};
const MAG={damage:.06,attackPower:.06,positional:.12,crit:.10,attackSpeed:.08,critDamage:.06};
function has(cls,list){return list.includes(cls)||list.includes(cls.replace(/\s+/g,''))}
function classSynergy(c){const x=identity(c),cls=x.cls.toLowerCase();if(x.role==='Support')return{};const out={};for(const[k,list]of Object.entries(SYNERGY))if(has(cls,list))out[k]=MAG[k];return out}
function supportEffects(c){const cls=identity(c).cls.toLowerCase();if(cls==='bard')return{supportAmplification:.095,attackSpeed:.08,critDamage:.03};if(cls==='artist')return{supportAmplification:.092,mana:.06,attackSpeed:.04};if(cls==='paladin')return{supportAmplification:.100,damage:.03};if(cls==='valkyrie')return{supportAmplification:.095,attackSpeed:.06};return{supportAmplification:.09}}
function sensitivity(c,s){const t=buildText(c).toLowerCase(),cls=identity(c).cls.toLowerCase();let v=1;if(s==='crit'){if(/adrenaline|keen blunt/.test(t))v+=.35;if(/100.?% crit|full crit/.test(t))v-=.20}if(s==='critDamage'&&/keen blunt|burst/.test(t))v+=.30;if(s==='attackSpeed'&&/raid captain|mass increase|wardancer|striker/.test(t))v+=.30;if(s==='positional'&&/ambush master|master brawler|deathblade|reaper|scrapper|entropy/.test(t))v+=.40;if(s==='mana'&&/summoner|mp|mana|max mp|nightmare/.test(t))v+=.45;if(s==='supportAmplification'&&/burst|grudge|adrenaline|keen blunt/.test(t))v+=.15;if(cls==='summoner'&&s==='mana')v+=.45;return Math.max(.60,v)}
function score(p){if(p.length!==4)return 0;const supports=p.filter(c=>identity(c).role==='Support');if(supports.length!==1)return 0;const dps=p.filter(c=>identity(c).role==='DPS');const base=p.reduce((n,c)=>n+identity(c).cp,0);if(!base)return 0;let mult=1;for(const src of dps){for(const[s,w]of Object.entries(classSynergy(src))){const targets=dps.filter(x=>x!==src);if(!targets.length)continue;const avg=targets.reduce((n,x)=>n+w*sensitivity(x,s),0)/targets.length;mult*=1+avg}}const sup=supports[0];for(const[s,w]of Object.entries(supportEffects(sup))){const avg=dps.length?dps.reduce((n,x)=>n+sensitivity(x,s),0)/dps.length:1;mult*=1+avg*w}return base*mult}
function resolve(a){const m=new Map(chars().map(c=>[c.id,c])),p1=[],p2=[],used=new Set();for(const id of a.party1||[]){if(m.has(id)&&!used.has(id)&&p1.length<4){p1.push(m.get(id));used.add(id)}}for(const id of a.party2||[]){if(m.has(id)&&!used.has(id)&&p2.length<4){p2.push(m.get(id));used.add(id)}}for(const c of m.values())if(!used.has(c.id)){if(p1.length<4){p1.push(c);used.add(c.id)}else if(p2.length<4){p2.push(c);used.add(c.id)}}return{p1,p2}}
function syn(p){const out=[];for(const c of p){for(const k of Object.keys(classSynergy(c)))if(!out.includes(k))out.push(k);if(identity(c).role==='Support'&&!out.includes('support amplification'))out.push('support amplification');if(identity(c).role==='Support'&&identity(c).cls.toLowerCase()==='artist'&&!out.includes('mana'))out.push('mana')}return out.map(s=>s==='attackPower'?'attack power':s)}
function member(c){const x=identity(c),col=x.role==='DPS'?'#e07a7a':'#79c98b';return `<div class="party-member authoritative-member" draggable="true" data-character-id="${esc(c.id)}"><a class="party-character-link" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${esc(x.name)}</a><span class="party-class-label">${esc(x.cls)}</span><span class="party-role-label" style="color:${col} !important">${x.role}</span><span class="party-stat-label">iLvl ${x.il} · CP ${x.cp}</span></div>`}
function render(a,msg=''){const h=document.querySelector('#suggestedParties');if(!h)return;const{p1,p2}=resolve(a),box=(n,k,p)=>`<article class="party authoritative-party" data-party="${k}"><div class="party-heading"><div><h3>${n}</h3><div class="party-score">Estimated potential: <strong>${fmt(score(p))}</strong></div></div><div class="party-meta">${p.length}/4 · ${p.filter(c=>identity(c).role==='Support').length} support</div></div><div class="party-dropzone authoritative-dropzone" data-drop-party="${k}">${p.map(member).join('')}</div><div class="party-synergies"><strong>Synergies:</strong> ${syn(p).join(', ')||'None'}</div></article>`;h.innerHTML=`<div class="authoritative-summary"><strong>Combined estimated potential: ${fmt(score(p1)+score(p2))}</strong><span> — Build-aware individual power with character-specific party synergy interactions.</span></div>${box('Party 1','party1',p1)}${box('Party 2','party2',p2)}${msg}`}
function combinations(a,k){const out=[];function r(i,p){if(p.length===k){out.push(p.slice());return}for(let j=i;j<=a.length-(k-p.length);j++)r(j+1,p.concat(a[j]))}r(0,[]);return out}
async function enrich(){const s=state();for(const c of s.characters||[]){if(!c.profile)continue;try{const r=await fetch(`${CONNECTOR}?url=${encodeURIComponent(c.url)}`,{cache:'no-store'});if(!r.ok)continue;const d=await r.json();c.profile.optimizerBuild={text:norm(d.html||d.characterHtml||d.content||'')}}catch{}}localStorage.setItem(STORAGE,JSON.stringify(s))}
async function optimize(){const b=document.querySelector('#optimizeBtn'),list=chars();if(list.length<8){render(assignments(),'<div class="optimizer-result">Add at least 8 characters to optimize parties.</div>');return}if(b){b.disabled=true;b.textContent='Optimizing…'}try{await enrich();const fresh=chars(),pool=fresh.length>14?fresh.slice().sort((a,c)=>identity(c).cp-identity(a).cp).slice(0,12):fresh;let best=null,high=-Infinity;for(const eight of combinations(pool,8))for(const p1 of combinations(eight,4)){const p2=eight.filter(c=>!p1.includes(c));if(p1.filter(c=>identity(c).role==='Support').length!==1||p2.filter(c=>identity(c).role==='Support').length!==1)continue;const s=score(p1)+score(p2);if(s>high){high=s;best={party1:p1.map(c=>c.id),party2:p2.map(c=>c.id)}}}if(!best)throw Error('No valid 4/4 arrangement with one support per party.');save(best);render(best,`<div class="optimizer-result"><strong>Optimization complete.</strong> Best build-aware 8-character arrangement: <strong>${fmt(high)}</strong>.</div>`)}catch(e){console.error(e);render(assignments(),'<div class="optimizer-result">Optimization failed. Current parties preserved.</div>')}finally{if(b){b.disabled=false;b.textContent='Optimize Parties'}}}
function wire(h){h.addEventListener('dragstart',e=>{const m=e.target.closest('.party-member');if(m)e.dataTransfer.setData('text/plain',m.dataset.characterId)});h.addEventListener('dragover',e=>{if(e.target.closest('.party-dropzone'))e.preventDefault()});h.addEventListener('drop',e=>{const z=e.target.closest('.party-dropzone');if(!z)return;e.preventDefault();const id=e.dataTransfer.getData('text/plain'),a=assignments(),from=a.party1.includes(id)?'party1':a.party2.includes(id)?'party2':null,to=z.dataset.dropParty;if(!from)return;const target=e.target.closest('.party-member');if(target&&target.dataset.characterId!==id){const other=target.dataset.characterId,of=a.party1.includes(other)?'party1':a.party2.includes(other)?'party2':null;if(!of||of===from)return;const i=a[from].indexOf(id),j=a[of].indexOf(other);a[from][i]=other;a[of][j]=id}else if(to!==from&&a[to].length<4){a[from]=a[from].filter(x=>x!==id);a[to].push(id)}else return;const old=resolve(assignments()),before=score(old.p1)+score(old.p2);save(a);const now=resolve(a),after=score(now.p1)+score(now.p2),delta=before?((after-before)/before)*100:0;render(a,`<div class="swap-impact ${delta>=0?'positive':'negative'}"><span class="swap-impact-number">${pct(delta)} combined estimated potential damage.</span></div>`)})}
function start(){const h=document.querySelector('#suggestedParties'),b=document.querySelector('#optimizeBtn');if(!h||!b||h.dataset.optimizerV10)return;h.dataset.optimizerV10='1';b.addEventListener('click',optimize);wire(h);render(assignments())}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();})();