/* Lost Ark Hideout — stable party optimizer + drag/drop. */
(()=>{
const STORAGE='lostark-hideout-private-v3',PARTY='lostark-hideout-party-assignments-v2';
const SUPPORTS=new Set(['Bard','Artist','Paladin','Valkyrie']);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Math.round(Number(n)||0).toLocaleString();
function state(){try{return JSON.parse(localStorage.getItem(STORAGE)||'null')||{characters:[]}}catch{return{characters:[]}}}
function chars(){return (state().characters||[]).filter(c=>c&&c.profile)}
function assignments(){try{const a=JSON.parse(localStorage.getItem(PARTY)||'null');if(a&&Array.isArray(a.party1)&&Array.isArray(a.party2))return a}catch{}return{party1:[],party2:[]}}
function save(a){localStorage.setItem(PARTY,JSON.stringify(a))}
function identity(c){const p=c.profile||{},card=[...document.querySelectorAll('#roster .character')].find(x=>x.querySelector('.remove-character')?.dataset.id===c.id),cls=(card?.querySelector('.class')?.textContent||p.class||'Unknown').trim();return{name:card?.querySelector('.character-bible-link')?.textContent?.trim()||p.name||c.name||'',cls,role:p.role==='Support'||SUPPORTS.has(cls)?'Support':'DPS',icon:card?.querySelector('img.class-icon')?.currentSrc||card?.querySelector('img.class-icon')?.src||'',il:Number(p.ilvl)||0,cp:Number(p.cp)||0}}
function traits(c){return c.profile?.optimizerBuild?.traits||{}}
function effects(c){const x=identity(c);if(x.role==='Support'){if(x.cls==='Bard')return{supportAmplification:.050,attackSpeed:.007};if(x.cls==='Artist')return{supportAmplification:.047,mana:.004};if(x.cls==='Paladin')return{supportAmplification:.052,damage:.003};if(x.cls==='Valkyrie')return{supportAmplification:.049,attackSpeed:.004};return{supportAmplification:.045}}switch(x.cls){case'Wardancer':case'Striker':return{crit:.010,attackSpeed:.005};case'Glaivier':case'Glavier':return{crit:.010,critDamage:.008};case'Deathblade':return{positional:.008,attackSpeed:.005};case'Gunslinger':case'Deadeye':case'Arcanist':case'Arcana':case'Aeromancer':return{crit:.010};case'Gunlancer':return{damage:.010,positional:.008};case'Soulfist':case'Machinist':return{attackPower:.007};default:return{damage:.010}}}
function affinity(c,s){const t=traits(c),x=identity(c);let n=1;if(s==='crit'&&t.critSensitive)n*=1.35;if(s==='critDamage'&&t.critDamageSensitive)n*=1.30;if(s==='attackSpeed'&&t.attackSpeedSensitive)n*=1.20;if(s==='positional'&&t.positional)n*=1.35;if(s==='mana'&&t.manaSensitive)n*=1.30;if(s==='damage'&&t.burst)n*=1.15;if(s==='supportAmplification'){if(t.burst)n*=1.18;if(t.partyAmplification)n*=1.08}if(x.role==='Support')n=0;return n}
function score(p){if(p.length!==4)return 0;const supports=p.filter(c=>identity(c).role==='Support');if(supports.length!==1)return 0;const dps=p.filter(c=>identity(c).role==='DPS');let base=p.reduce((n,c)=>n+identity(c).cp,0),mult=1;for(const src of dps){for(const [s,w] of Object.entries(effects(src))){const targets=dps.filter(x=>x!==src);if(targets.length)mult*=1+w*(targets.reduce((n,x)=>n+affinity(x,s),0)/targets.length)}}for(const [s,w] of Object.entries(effects(supports[0]))){const avg=dps.reduce((n,x)=>n+affinity(x,s),0)/Math.max(1,dps.length);mult*=1+w*avg}return base*mult}
function resolve(a){const m=new Map(chars().map(c=>[c.id,c])),p1=[],p2=[],used=new Set();for(const x of a.party1){if(m.has(x)&&!used.has(x)&&p1.length<4){p1.push(m.get(x));used.add(x)}}for(const x of a.party2){if(m.has(x)&&!used.has(x)&&p2.length<4){p2.push(m.get(x));used.add(x)}}for(const c of m.values())if(!used.has(c.id)){if(p1.length<4){p1.push(c);used.add(c.id)}else if(p2.length<4){p2.push(c);used.add(c.id)}}return{p1,p2}}
function member(c){const x=identity(c),col=x.role==='DPS'?'#e07a7a':'#79c98b';return `<div class="party-member authoritative-member" draggable="true" data-character-id="${esc(c.id)}"><a class="party-character-link" href="${esc(c.url)}" target="_blank" rel="noopener noreferrer">${x.icon?`<img class="class-icon" src="${esc(x.icon)}" alt="${esc(x.cls)}">`:''}${esc(x.name)}</a><span class="party-class-label">${esc(x.cls)}</span><span class="party-role-label" style="color:${col} !important">${x.role}</span><span class="party-stat-label">iLvl ${x.il} · CP ${x.cp}</span></div>`}
function syn(p){const out=[];for(const c of p)for(const k of Object.keys(effects(c))){const s=k==='supportAmplification'?'support amplification':k;if(!out.includes(s))out.push(s)}return out}
function render(a,msg=''){const h=document.querySelector('#suggestedParties');if(!h)return;const {p1,p2}=resolve(a);const box=(n,k,p)=>`<article class="party" data-party="${k}"><div class="party-heading"><div><h3>${n}</h3><div class="party-score">Estimated potential: <strong>${fmt(score(p))}</strong></div></div><div class="party-meta">${p.length}/4 · ${p.filter(c=>identity(c).role==='Support').length} support</div></div><div class="party-dropzone" data-drop-party="${k}">${p.map(member).join('')}</div><div class="party-synergies"><strong>Synergies:</strong> ${syn(p).join(', ')||'None'}</div></article>`;h.innerHTML=`<div class="authoritative-summary"><strong>Combined estimated potential: ${fmt(score(p1)+score(p2))}</strong><span> — CP-based individual power with build-aware party synergy interactions. Higher is better; not a literal in-game DPS value.</span></div><div class="authoritative-parties">${box('Party 1','party1',p1)}${box('Party 2','party2',p2)}</div>${msg}`}
function combinations(a,k){const out=[];function r(i,p){if(p.length===k){out.push(p.slice());return}for(let j=i;j<=a.length-(k-p.length);j++)r(j+1,p.concat(a[j]))}r(0,[]);return out}
async function optimize(){const list=chars(),b=document.querySelector('#optimizeBtn');if(list.length<8){render(assignments(),'<div class="optimizer-result">Add at least 8 characters to optimize parties.</div>');return}if(b){b.disabled=true;b.textContent='Optimizing…'}try{let best=null,high=-Infinity;const pools=list.length>14?[list.slice().sort((a,c)=>identity(c).cp-identity(a).cp).slice(0,8)]:combinations(list,8);for(const eight of pools)for(const p1 of combinations(eight,4)){const p2=eight.filter(c=>!p1.includes(c));if(p1.filter(c=>identity(c).role==='Support').length!==1||p2.filter(c=>identity(c).role==='Support').length!==1)continue;const s=score(p1)+score(p2);if(s>high){high=s;best={party1:p1.map(c=>c.id),party2:p2.map(c=>c.id)}}}if(best){save(best);render(best,`<div class="optimizer-result"><strong>Optimization complete.</strong> Best valid 8-character arrangement: <strong>${fmt(high)}</strong>.</div>`)}else render(assignments(),'<div class="optimizer-result">No valid 4/4 arrangement with exactly one support per party was found.</div>')}catch(err){render(assignments(),'<div class="optimizer-result">Optimization failed. The current party arrangement was preserved.</div>');console.error('Lost Ark Hideout optimizer error',err)}finally{if(b){b.disabled=false;b.textContent='Optimize Parties'}}}
function wire(h){h.addEventListener('dragstart',e=>{const m=e.target.closest('.party-member');if(m)e.dataTransfer.setData('text/plain',m.dataset.characterId)});h.addEventListener('dragover',e=>{if(e.target.closest('.party-dropzone'))e.preventDefault()});h.addEventListener('drop',e=>{const z=e.target.closest('.party-dropzone');if(!z)return;e.preventDefault();const idv=e.dataTransfer.getData('text/plain'),a=assignments(),from=a.party1.includes(idv)?'party1':a.party2.includes(idv)?'party2':null;if(!from)return;const target=e.target.closest('.party-member'),to=z.dataset.dropParty;if(target&&target.dataset.characterId!==idv){const other=target.dataset.characterId,of=a.party1.includes(other)?'party1':a.party2.includes(other)?'party2':null;if(!of||of===from)return;const i=a[from].indexOf(idv),j=a[of].indexOf(other);a[from][i]=other;a[of][j]=idv}else if(to!==from&&a[to].length<4){a[from]=a[from].filter(x=>x!==idv);a[to].push(idv)}else return;const old=assignments();const before=score(resolve(old).p1)+score(resolve(old).p2);save(a);const after=score(resolve(a).p1)+score(resolve(a).p2),pct=before?((after-before)/before)*100:0;render(a,`<div class="swap-impact ${pct>=0?'positive':'negative'}">${pct>=0?'+':''}${pct.toFixed(2)}% combined estimated potential damage.</div>`)})}
function start(){const h=document.querySelector('#suggestedParties'),b=document.querySelector('#optimizeBtn');if(!h||!b||h.dataset.optimizerStable)return;h.dataset.optimizerStable='1';b.addEventListener('click',optimize);wire(h);render(assignments())}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();})();
