/* Lost Ark Hideout — single owner for party rendering, drag/drop, and build-aware optimization. */
(()=>{
const STORAGE='lostark-hideout-private-v3', PARTY='lostark-hideout-party-assignments-v2';
const CONNECTOR='https://lostark-bible-connector.seraph0226.workers.dev/character';
const SUPPORTS=new Set(['Bard','Artist','Paladin','Valkyrie']);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
const fmt=n=>Math.round(Number(n)||0).toLocaleString();
function readState(){try{return JSON.parse(localStorage.getItem(STORAGE)||'null')||{characters:[]}}catch{return{characters:[]}}}
function readAssignments(){try{const a=JSON.parse(localStorage.getItem(PARTY)||'null');if(Array.isArray(a?.party1)&&Array.isArray(a?.party2))return a}catch{}return{party1:[],party2:[]}}
function writeAssignments(a){localStorage.setItem(PARTY,JSON.stringify(a))}
function characters(){return readState().characters.filter(c=>c?.profile)}
function identity(c){const card=[...document.querySelectorAll('#roster .character')].find(x=>x.querySelector('.remove-character')?.dataset.id===c.id||norm(x.querySelector('.character-bible-link')?.getAttribute('href'))===norm(c.url));const p=c.profile||{};const name=card?.querySelector('.character-bible-link')?.textContent?.trim()||p.name||c.name||'';const cls=(card?.querySelector('.class')?.textContent||p.class||'Unknown').trim();const img=card?.querySelector('img.class-icon');const role=p.role==='Support'||SUPPORTS.has(cls)?'Support':'DPS';const il=Number(p.ilvl)||0,cp=Number(p.cp)||0;return{name,cls,role,icon:img?.currentSrc||img?.src||'',il,cp}}
function buildTraits(c){return c.profile?.optimizerBuild?.traits||{}}
function synergyFor(c){switch(identity(c).cls){case'Wardancer':case'Striker':return['crit','attackSpeed'];case'Glaivier':case'Glavier':return['crit','critDamage'];case'Deathblade':return['positional','attackSpeed'];case'Gunslinger':case'Deadeye':case'Arcanist':case'Arcana':case'Aeromancer':return['crit'];case'Gunlancer':return['damage','positional'];case'Soulfist':case'Machinist':return['attackPower'];case'Bard':return['supportAmplification','attackSpeed'];case'Artist':return['supportAmplification','mana'];case'Paladin':return['supportAmplification','damage'];case'Valkyrie':return['supportAmplification','attackSpeed'];default:return['damage']}}
const WEIGHT={damage:.010,crit:.010,critDamage:.008,attackPower:.007,attackSpeed:.005,positional:.008,mana:.002,supportAmplification:.045};
const SUPPORT_WEIGHT={Bard:{supportAmplification:.050,attackSpeed:.007},Artist:{supportAmplification:.047,mana:.004},Paladin:{supportAmplification:.052,damage:.003},Valkyrie:{supportAmplification:.049,attackSpeed:.004}};
function affinity(c,s){const t=buildTraits(c);let x=1;if(s==='crit'&&t.critSensitive)x*=1.35;if(s==='critDamage'&&t.critDamageSensitive)x*=1.30;if(s==='attackSpeed'&&t.attackSpeedSensitive)x*=1.20;if(s==='positional'&&t.positional)x*=1.35;if(s==='mana'&&t.manaSensitive)x*=1.30;if(s==='damage'){if(t.burst)x*=1.15;if(t.summon)x*=1.05}if(s==='attackPower'&&t.critSensitive)x*=1.03;if(s==='supportAmplification'){if(t.burst)x*=1.18;if(t.partyAmplification)x*=1.08}return x}
function sourceEffects(src){const x=identity(src);if(x.role==='Support')return Object.entries(SUPPORT_WEIGHT[x.cls]||{supportAmplification:.045});const out={};for(const s of synergyFor(src))out[s]=WEIGHT[s]||0;return out}
function partyScore(p){if(p.length!==4)return 0;if(new Set(p.map(c=>c.id)).size!==4)return 0;if(p.filter(c=>identity(c).role==='Support').length!==1)return 0;const ids=p.map(identity),support=p.find(c=>identity(c).role==='Support'),dps=p.filter(c=>identity(c).role==='DPS');let total=ids.reduce((n,x)=>n+x.cp,0),mult=1;
for(const src of p){const sx=identity(src);if(sx.role==='Support')continue;const effects=sourceEffects(src);for(const [s,w] of Object.entries(effects)){const targets=dps.filter(x=>x.id!==sx.id);if(!targets.length)continue;const key=`${sx.cls}:${s}`;const avg=targets.reduce((n,x)=>n+affinity(p.find(c=>identity(c).id===x.id),s),0)/targets.length;mult*=1+w*avg}}
if(support){const sx=identity(support),effects=sourceEffects(support);for(const [s,w] of Object.entries(effects)){const avg=dps.reduce((n,x)=>n+affinity(p.find(c=>identity(c).id===x.id),s),0)/dps.length;mult*=1+w*avg}}
return total*mult}
function resolve(a){const map=new Map(characters().map(c=>[c.id,c])),p1=[],p2=[],seen=new Set();for(const id of a.party1||[]){if(map.has(id)&&!seen.has(id)&&p1.length<4){p1.push(map.get(id));seen.add(id)}}for(const id of a.party2||[]){if(map.has(id)&&!seen.has(id)&&p2.length<4){p2.push(map.get(id));seen.add(id)}}for(const c of map.values()){if(seen.has(c.id))continue;if(p1.length<4){p1.push(c);seen.add(c.id)}else if(p2.length<4){p2.push(c);seen.add(c.id)}}return{p1,p2}}
function member(c){const x=identity(c),color=x.role==='DPS'?'#e07a7a':'#79c98b';return `<div class="party-member authoritative-member" draggable="true" data-character-id="${esc(c.id)}"><div class="party-member-main"><a class="party-character-link" href="${esc(c.url)}" target="_blank" rel="noopener noreferrer">${x.icon?`<img class="class-icon" src="${esc(x.icon)}" alt="${esc(x.cls)}">`:''}${esc(x.name)}</a><span class="party-class-label">${esc(x.cls)}</span><span class="party-role-label" style="color:${color} !important">${x.role}</span><span class="party-stat-label">iLvl ${x.il.toLocaleString(undefined,{maximumFractionDigits:2})} · CP ${x.cp.toLocaleString(undefined,{maximumFractionDigits:2})}</span></div></div>`}
function synergyList(p){const out=[];for(const c of p)for(const s of Object.keys(sourceEffects(c))){const label=s==='supportAmplification'?'support amplification':s;if(!out.includes(label))out.push(label)}return out}
function render(a,extra=''){const host=document.querySelector('#suggestedParties');if(!host)return;const {p1,p2}=resolve(a);if(!p1.length&&!p2.length){host.innerHTML='<div class="empty-roster">Add specific character profiles to generate the party setup.</div>';return}const party=(name,id,p)=>`<article class="party authoritative-party" data-party="${id}"><div class="party-heading"><div><h3>${name}</h3><div class="party-score">Estimated potential: <strong>${fmt(partyScore(p))}</strong></div></div><div class="party-meta">${p.length}/4 · ${p.filter(c=>identity(c).role==='Support').length} support</div></div><div class="party-dropzone authoritative-dropzone" data-drop-party="${id}">${p.length?p.map(member).join(''):'<div class="party-empty">Drop a character here</div>'}</div><div class="party-synergies"><strong>Synergies:</strong> ${synergyList(p).map(esc).join(', ')||'None'}</div></article>`;host.innerHTML=`<div class="authoritative-summary"><strong>Combined estimated potential: ${fmt(partyScore(p1)+partyScore(p2))}</strong><span class="potential-explanation"> — CP-based individual power with build-aware party synergy interactions. Higher is better; not a literal in-game DPS value.</span></div><div class="authoritative-parties">${party('Party 1','party1',p1)}${party('Party 2','party2',p2)}</div>${extra}`}
function partyOf(id,a){return a.party1.includes(id)?'party1':a.party2.includes(id)?'party2':null}
function currentScore(a){const r=resolve(a);return partyScore(r.p1)+partyScore(r.p2)}
function dragWire(host){host.addEventListener('dragstart',e=>{const m=e.target.closest('.party-member');if(!m)return;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',m.dataset.characterId)});host.addEventListener('dragover',e=>{if(e.target.closest('.party-dropzone')){e.preventDefault();e.dataTransfer.dropEffect='move'}});host.addEventListener('drop',e=>{const zone=e.target.closest('.party-dropzone');if(!zone)return;e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(!id)return;const target=e.target.closest('.party-member');const a=readAssignments(),from=partyOf(id,a),to=zone.dataset.dropParty;if(!from)return;const before=currentScore(a);if(target&&target.dataset.characterId!==id){const other=target.dataset.characterId,otherParty=partyOf(other,a);if(otherParty&&otherParty!==from){const i=a[from].indexOf(id),j=a[otherParty].indexOf(other);a[from][i]=other;a[otherParty][j]=id}else return}else if(to!==from&&a[to].length<4){a[from]=a[from].filter(x=>x!==id);a[to].push(id)}else return;writeAssignments(a);const after=currentScore(a),pct=before?((after-before)/before)*100:0;render(a,`<div class="swap-impact ${pct>=0?'positive':'negative'}">${pct>=0?'+':''}${pct.toFixed(2)}% combined estimated potential damage.</div>`)})}
function combinations(arr,k,start=0,p=[],out=[]){if(p.length===k){out.push(p.slice());return out}for(let i=start;i<=arr.length-(k-p.length);i++)combinations(arr,k,i+1,p.concat(arr[i]),out);return out}
function applyBuildFallback(c){if(c.profile?.optimizerBuild)return;c.profile.optimizerBuild={traits:{},sourceUrl:c.url}}
function parseBuild(html,c){const d=new DOMParser().parseFromString(html,'text/html'),t=(d.body?.textContent||'').toLowerCase(),p=c.profile||{},stats={crit:0,swiftness:0,specialization:0};for(const [k,re] of [['crit',/crit\s+lv\.\s*(\d+)/i],['swiftness',/swiftness\s+lv\.\s*(\d+)/i],['specialization',/specialization\s+lv\.\s*(\d+)/i]]){const m=(d.body?.textContent||'').match(re);if(m)stats[k]=Number(m[1])}const coreWords=t.match(/ark grid[\s\S]{0,12000}/i)?.[0]||'';const traits={critSensitive:/crit|critical|keen blunt|adrenaline/.test(t)||stats.crit>=8,critDamageSensitive:/crit damage|critical damage|keen blunt/.test(t),attackSpeedSensitive:/attack speed|swiftness|mass increase|raid captain/.test(t)||stats.swiftness>=15,positional:/back attack|head attack|ambush master|master brawler|positional/.test(t),manaSensitive:/mana|max mp|mp recovery|mp regen/.test(t),cooldownSensitive:/cooldown|quick recharge/.test(t)||stats.swiftness>=15,burst:/burst|surge|deathblow|punisher/.test(coreWords),summon:/summon|elemental|entwinement|command awakening/.test(coreWords),partyAmplification:/ally damage|party members|support amplification/.test(t)};p.optimizerBuild={traits,stats,sourceUrl:c.url,retrievedAt:new Date().toISOString()};c.profile=p}
async function enrichAll(list){for(const c of list){applyBuildFallback(c);if(c.profile.optimizerBuild.sourceUrl===c.url)continue;try{const r=await fetch(`${CONNECTOR}?url=${encodeURIComponent(c.url)}`,{cache:'no-store',headers:{Accept:'application/json'}});const d=await r.json();if(r.ok&&d.ok!==false)parseBuild(d.html||d.characterHtml||d.content||d.page,c)}catch{}}localStorage.setItem(STORAGE,JSON.stringify(readState()))}
async function optimize(){const list=characters();if(list.length<8){render(readAssignments(),'<div class="optimizer-result">Add at least 8 characters to optimize parties.</div>');return}const btn=document.querySelector('#optimizeBtn');if(btn)btn.disabled=true;try{await enrichAll(list);const roster=characters(),eights=roster.length<=14?combinations(roster,8):[roster.slice().sort((a,b)=>identity(b).cp-identity(a).cp).slice(0,8)];let best=null,bestScore=-Infinity;for(const eight of eights)for(const p1 of combinations(eight,4)){const p2=eight.filter(c=>!p1.includes(c));if(p1.filter(c=>identity(c).role==='Support').length!==1||p2.filter(c=>identity(c).role==='Support').length!==1)continue;const s=partyScore(p1)+partyScore(p2);if(s>bestScore){bestScore=s;best={party1:p1.map(c=>c.id),party2:p2.map(c=>c.id)}}}if(best){writeAssignments(best);render(best,`<div class="optimizer-result"><strong>Optimization complete.</strong> Best valid 8-character arrangement: <strong>${fmt(bestScore)}</strong>.</div>`)}}finally{if(btn)btn.disabled=false}}
function start(){const host=document.querySelector('#suggestedParties'),btn=document.querySelector('#optimizeBtn');if(!host||!btn)return;if(host.dataset.v7==='1')return;host.dataset.v7='1';btn.addEventListener('click',optimize);dragWire(host);render(readAssignments());}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
