/* Lost Ark Hideout: authoritative character -> class icons. */
(()=>{
  const CHARACTER_CLASS={seraphh:'Summoner',ryohaku:'Glavier',hetawl:'Berserker',badmechanics:'Wardancer',ihzanami:'Bard',bailsxo:'Artist',trashtierweeb:'Scrapper','diamarté':'Soul Eater',diamarte:'Soul Eater'};
  const ICONS={Berserker:'berserker',Destroyer:'destroyer',Gunlancer:'gunlancer',Paladin:'paladin',Slayer:'slayer',Arcanist:'arcanist',Arcana:'arcana',Summoner:'summoner',Sorceress:'sorceress',Bard:'bard',Gunslinger:'gunslinger',Deadeye:'deadeye',Sharpshooter:'sharpshooter',Artillerist:'artillerist',Machinist:'machinist',Striker:'striker',Wardancer:'wardancer',Scrapper:'scrapper',Soulfist:'soulfist',Glavier:'glavier',Glaivier:'glavier',Deathblade:'deathblade',Shadowhunter:'shadowhunter',Reaper:'reaper',Artist:'artist',Aeromancer:'aeromancer',Breaker:'breaker',Valkyrie:'valkyrie','Soul Eater':'soul-eater',Souleater:'soul-eater'};
  const normalize=v=>String(v||'').trim().toLowerCase();
  const classFor=(name,displayed)=>CHARACTER_CLASS[normalize(name)]||displayed||'';
  const iconUrl=cls=>ICONS[cls]?`https://lostark.bible/_next/image?url=%2Fimages%2Fclasses%2F${ICONS[cls]}.png&w=64&q=75`:'';
  const makeIcon=cls=>{const src=iconUrl(cls);if(!src)return null;const img=document.createElement('img');img.className='class-icon';img.alt=`${cls} icon`;img.src=src;img.width=28;img.height=28;img.loading='eager';img.decoding='async';img.style.cssText='width:28px;height:28px;display:inline-block!important;vertical-align:middle;object-fit:contain;margin-right:8px;flex:0 0 28px;';return img};
  function repairRoster(){document.querySelectorAll('.character').forEach(card=>{const link=card.querySelector('.character-bible-link');const h3=card.querySelector('.character-head h3');if(!h3)return;const name=link?.textContent?.trim()||'';const cls=classFor(name,card.querySelector('.class')?.textContent?.trim());if(!cls)return;const label=card.querySelector('.class');if(label){label.textContent=cls;label.querySelectorAll('.class-icon').forEach(x=>x.remove())}h3.querySelectorAll('.class-icon').forEach(x=>x.remove());const img=makeIcon(cls);if(img)h3.insertBefore(img,h3.firstChild)})}
  function repairParties(){document.querySelectorAll('#suggestedParties .slot').forEach(slot=>{const h4=slot.querySelector('h4');if(!h4)return;const name=h4.textContent.trim();const small=slot.querySelector('small');const displayed=small?.textContent?.split('·')[0]?.trim()||'';const cls=classFor(name,displayed);if(!cls)return;h4.querySelectorAll('.class-icon').forEach(x=>x.remove());const img=makeIcon(cls);if(img)h4.insertBefore(img,h4.firstChild);if(small){const parts=small.textContent.split('·');parts[0]=` ${cls} `;small.textContent=parts.join('·')}})}
  function repair(){repairRoster();repairParties()}
  let queued=false;const schedule=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;repair()})};const observer=new MutationObserver(schedule);function start(){repair();observer.observe(document.body,{childList:true,subtree:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();