/* Lower-party icon bridge only. The roster is rendered by app-fixed.js; this file must not touch it. */
(()=>{
  const ALIASES={Arcana:'arcanist',Glaivier:'glavier','Soul Eater':'soul-eater',Souleater:'soul-eater','Guardian Knight':'guardian-knight',GuardianKnight:'guardian-knight'};
  const iconUrl=cls=>{const c=String(cls||'').trim();if(!c||c==='Unknown'||c==='Profile pending'||c==='—')return '';const slug=ALIASES[c]||c.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');return `https://lostark.bible/_next/image?url=${encodeURIComponent(`/images/classes/${slug}.png`)}&w=64&q=75`};
  const classes=['Berserker','Destroyer','Gunlancer','Paladin','Slayer','Arcanist','Arcana','Summoner','Sorceress','Bard','Gunslinger','Deadeye','Sharpshooter','Artillerist','Machinist','Striker','Wardancer','Scrapper','Soulfist','Glavier','Glaivier','Deathblade','Shadowhunter','Reaper','Artist','Aeromancer','Breaker','Valkyrie','Soul Eater','Souleater','Wildsoul','Guardian Knight','GuardianKnight'];
  const findClass=t=>{const s=String(t||'');return classes.slice().sort((a,b)=>b.length-a.length).find(x=>new RegExp(`(?:^|[^A-Za-z])${x.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')}(?:[^A-Za-z]|$)`,'i').test(s))||''};
  function add(link,cls){if(!link||!cls)return;let img=link.querySelector(':scope>.class-icon');if(!img){img=document.createElement('img');img.className='class-icon';link.insertBefore(img,link.firstChild)}img.src=iconUrl(cls);img.alt='';img.width=18;img.height=18;img.loading='eager';img.decoding='async'}
  function repair(){document.querySelectorAll('#suggestedParties .party-member').forEach(m=>{const link=m.querySelector('.party-character-link'),meta=m.querySelector('.party-member-main>span');add(link,findClass(meta?.textContent))});document.querySelectorAll('#suggestedParties .slot').forEach(s=>{const h=s.querySelector('h4'),meta=s.querySelector('small');add(h,findClass(meta?.textContent))})}
  let queued=false;const schedule=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;repair()})};
  const observer=new MutationObserver(schedule);function start(){repair();observer.observe(document.body,{childList:true,subtree:true})};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();